// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries/orders.sql

package persistence

import (
	"context"
	"database/sql"

	"example.com/orderd/internal/services/orders"
)

// UpsertOrder is generated code sitting alongside hand-written code. The
// file carries the conventional "Code generated ... DO NOT EDIT." header, so
// the scanner skips it (issue #96) and these symbols do NOT land in the index
// — the golden snapshot pins that, and pins that hand-written siblings in the
// same package still do.
func UpsertOrder(_ context.Context, _ *sql.DB, _ string, _ string) error {
	return nil
}

// SelectOrder is the generated single-row read.
func SelectOrder(_ context.Context, _ *sql.DB, _ string) (*orders.Order, error) {
	return nil, orders.ErrNotFound
}
