// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries/orders.sql

package persistence

import (
	"context"
	"database/sql"

	"example.com/orderd/internal/services/orders"
)

// UpsertOrder is generated code sitting alongside hand-written code. The
// scanner has no "generated" header heuristic, so these symbols DO land in
// the index — the golden snapshot pins that.
func UpsertOrder(_ context.Context, _ *sql.DB, _ string, _ string) error {
	return nil
}

// SelectOrder is the generated single-row read.
func SelectOrder(_ context.Context, _ *sql.DB, _ string) (*orders.Order, error) {
	return nil, orders.ErrNotFound
}
