#!/usr/bin/env bash
# Generate the Homebrew formula for one published release.
#
# Issue #121 asks that `brew install` work on a tagged release. A formula for
# a pre-built binary is just four URLs and four digests, and this repository
# already publishes both: the release assets and the signed SHA256SUMS that
# covers them. So the formula is DERIVED from that manifest rather than
# hand-maintained — a hand-copied digest is a number nobody measured, and it
# would be wrong exactly once, silently, on the release nobody re-checked.
#
# What this script does NOT do is publish. A Homebrew tap is a second
# repository (`<owner>/homebrew-<tap>`), and creating one plus a token that
# can write to it is an operator decision. release.yml pushes the generated
# file when the operator has configured a tap and skips, loudly, when they
# have not. docs/releasing.md says which two settings that is.
#
# Usage:
#   brew-formula.sh --version vX.Y.Z --dist DIR [--repo owner/name] [--out FILE]
#
# --dist must contain the release's SHA256SUMS. Every digest in the output
# comes from that file; nothing is computed from thin air, and a missing
# platform is a hard failure rather than a formula that 404s on install.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "$SCRIPT_DIR/lib.sh"

VERSION=""
DIST=""
REPO="sosalejandro/atlas"
OUT="" # empty means stdout

while [ $# -gt 0 ]; do
	case "$1" in
	--version)
		VERSION="$2"
		shift 2
		;;
	--dist)
		DIST="$2"
		shift 2
		;;
	--repo)
		REPO="$2"
		shift 2
		;;
	--out)
		OUT="$2"
		shift 2
		;;
	*)
		atlas_err "unknown argument: $1"
		exit 2
		;;
	esac
done

if [ -z "$VERSION" ] || [ -z "$DIST" ]; then
	atlas_err "usage: brew-formula.sh --version vX.Y.Z --dist DIR [--repo owner/name] [--out FILE]"
	exit 2
fi

# Homebrew's `version` is the bare semver; the asset names carry the `v`.
if ! printf '%s' "$VERSION" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+([.-][A-Za-z0-9.-]+)?$'; then
	atlas_err "not a release tag: '$VERSION' (a formula can only name a published release)"
	exit 1
fi
bare="${VERSION#v}"

sums="$DIST/SHA256SUMS"
if [ ! -f "$sums" ]; then
	atlas_err "no SHA256SUMS in $DIST — the formula's digests must come from the release manifest"
	exit 1
fi

# digest_of prints the digest SHA256SUMS records for one asset name, and
# fails if the asset is not in the manifest. Homebrew resolves exactly one
# of these per machine, so a missing line would only surface as a failed
# `brew install` on whichever platform nobody tested.
digest_of() {
	local name="$1" line
	line="$(grep -E "[[:space:]]\*?${name}\$" "$sums" || true)"
	if [ -z "$line" ]; then
		atlas_err "asset not covered by SHA256SUMS: $name"
		return 1
	fi
	printf '%s\n' "$line" | awk '{print $1}'
}

darwin_arm64="$(digest_of "atlas_${VERSION}_darwin_arm64")"
darwin_amd64="$(digest_of "atlas_${VERSION}_darwin_amd64")"
linux_arm64="$(digest_of "atlas_${VERSION}_linux_arm64")"
linux_amd64="$(digest_of "atlas_${VERSION}_linux_amd64")"

base="https://github.com/${REPO}/releases/download/${VERSION}"

render() {
	cat <<FORMULA
# Generated by .github/scripts/brew-formula.sh for ${VERSION}. Do not edit by
# hand: every digest below is copied from that release's signed SHA256SUMS.
class Atlas < Formula
  desc "Capability registry and verification gate for a codebase"
  homepage "https://github.com/${REPO}"
  version "${bare}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${base}/atlas_${VERSION}_darwin_arm64"
      sha256 "${darwin_arm64}"
    end
    on_intel do
      url "${base}/atlas_${VERSION}_darwin_amd64"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/atlas_${VERSION}_linux_arm64"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "${base}/atlas_${VERSION}_linux_amd64"
      sha256 "${linux_amd64}"
    end
  end

  def install
    # `atlas_*` and not `atlas*`: the release also ships atlas-serve, and the
    # formula installs the CLI only. That is a decision, not an accident of
    # globbing -- atlas-serve exists for the desktop app, which ships its own
    # bundle, and a brew user installing a CLI has no use for a local HTTP
    # API they did not ask for. See issue #172.
    bin.install Dir["atlas_*"].first => "atlas"
  end

  test do
    assert_match "atlas", shell_output("#{bin}/atlas version")
  end
end
FORMULA
}

if [ -n "$OUT" ]; then
	mkdir -p "$(dirname "$OUT")"
	render >"$OUT"
	printf 'wrote %s for %s\n' "$OUT" "$VERSION" >&2
else
	render
fi
