package app

// MentionsGenerated is hand-written code that happens to quote the
// generated-file convention in its doc comment. The marker below sits
// after the package clause, so the header rule must not fire on it.
//
// Code generated by nothing at all. DO NOT EDIT.
func MentionsGenerated() string {
	return "hand"
}
