package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// generatedFixtureRoot is the scanner's own generated-code fixture:
// handwritten.go is hand-written, and its siblings are generated by header
// (db/queries.sql.go, generated/with_header.go), by directory
// (generated/legacy.go) and — with the config written below — by glob
// (api/schema.pb.go).
const generatedFixtureRoot = "../../packages/codeindex/go/testdata/generatedproject"

// skippedFixture is a temp DB plus a config that turns two of the fixture's
// files into glob matches. Both globs deliberately overlap a rule that is
// stronger than they are, so the ledger has something to get wrong.
type skippedFixture struct {
	dbPath     string
	configPath string
}

func newSkippedFixture(t *testing.T) *skippedFixture {
	t.Helper()
	dir := t.TempDir()
	cfg := filepath.Join(dir, "atlas.yaml")
	const body = `scan:
  generated:
    - "**/*.pb.go"
    - "**/*.sql.go"
`
	if err := os.WriteFile(cfg, []byte(body), 0o600); err != nil {
		t.Fatalf("write config: %v", err)
	}
	return &skippedFixture{dbPath: filepath.Join(dir, "atlas.db"), configPath: cfg}
}

func runScanCmd(t *testing.T, fix *skippedFixture, args ...string) (string, string, error) {
	t.Helper()
	root := NewRootCmd()
	var stdout, stderr bytes.Buffer
	root.SetOut(&stdout)
	root.SetErr(&stderr)
	root.SetArgs(append([]string{
		"scan",
		"--db-path", fix.dbPath,
		"--config", fix.configPath,
	}, args...))
	err := root.ExecuteContext(context.Background())
	return stdout.String(), stderr.String(), err
}

// The point of the ledger: after the scan that dropped a file has scrolled
// out of the terminal, the store still knows which rule dropped it.
func TestScanSkipped_ReadsTheLedgerBackWithoutRescanning(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("scan: %v\nstderr: %s", err, stderr)
	}

	stdout, stderr, err := runScanCmd(t, fix, "--skipped")
	if err != nil {
		t.Fatalf("scan --skipped: %v\nstderr: %s", err, stderr)
	}
	for _, want := range []string{
		"api/schema.pb.go", "generated-glob", "**/*.pb.go",
		"db/queries.sql.go", "generated-header",
		"generated/legacy.go", "generated-dir",
	} {
		if !strings.Contains(stdout, want) {
			t.Errorf("scan --skipped output missing %q:\n%s", want, stdout)
		}
	}
	// The read path must not walk the tree again — a scan summary line here
	// would mean the answer came from a fresh scan, not from the store.
	if strings.Contains(stdout, "files_scanned=") {
		t.Errorf("scan --skipped re-ran the scan:\n%s", stdout)
	}
}

// The rule recorded must be the one that CLAIMED the file. queries.sql.go
// carries the generated header AND matches `**/*.sql.go`; the scanner checks
// the header first (issue #96), and this ledger is the only place that
// ordering leaves a trace.
func TestScanSkipped_TwoRulesRecordTheClaimingRule(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("scan: %v\nstderr: %s", err, stderr)
	}

	entries := skippedJSON(t, fix, "--skipped")
	byPath := map[string]map[string]any{}
	for _, e := range entries {
		byPath[jsonStr(e["file_path"])] = e
	}

	sqlgo, ok := byPath["db/queries.sql.go"]
	if !ok {
		t.Fatalf("db/queries.sql.go missing from the ledger: %v", byPath)
	}
	if got := jsonStr(sqlgo["rule"]); got != "generated-header" {
		t.Errorf("db/queries.sql.go rule = %q, want generated-header "+
			"(the header rule claimed it; the glob only also matched)", got)
	}
	if got := jsonStr(sqlgo["detail"]); got != "" {
		t.Errorf("db/queries.sql.go detail = %q, want empty: naming the glob "+
			"would send the operator to a config line whose removal changes nothing", got)
	}

	// generated/with_header.go matches the header rule and the directory
	// rule. Same principle, the other pair.
	withHeader, ok := byPath["generated/with_header.go"]
	if !ok {
		t.Fatalf("generated/with_header.go missing from the ledger: %v", byPath)
	}
	if got := jsonStr(withHeader["rule"]); got != "generated-header" {
		t.Errorf("generated/with_header.go rule = %q, want generated-header", got)
	}

	// And the glob case names the pattern, which is the whole reason the
	// reason is not just "generated".
	pb, ok := byPath["api/schema.pb.go"]
	if !ok {
		t.Fatalf("api/schema.pb.go missing from the ledger: %v", byPath)
	}
	if got := jsonStr(pb["rule"]); got != "generated-glob" {
		t.Errorf("api/schema.pb.go rule = %q, want generated-glob", got)
	}
	if got := jsonStr(pb["detail"]); got != "**/*.pb.go" {
		t.Errorf("api/schema.pb.go detail = %q, want **/*.pb.go", got)
	}
}

// A file that stops being skipped must leave the ledger, or the ledger
// becomes a record of every rule ever tried.
func TestScanSkipped_ReplacedNotAppended(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("first scan: %v\nstderr: %s", err, stderr)
	}
	if n := len(skippedJSON(t, fix, "--skipped")); n == 0 {
		t.Fatal("first scan recorded nothing")
	}

	if _, stderr, err := runScanCmd(t, fix,
		"--root", generatedFixtureRoot, "--include-generated"); err != nil {
		t.Fatalf("second scan: %v\nstderr: %s", err, stderr)
	}
	if entries := skippedJSON(t, fix, "--skipped"); len(entries) != 0 {
		t.Fatalf("ledger after --include-generated = %v, want empty", entries)
	}
}

// One-file lookup: the question an operator actually asks.
func TestScanSkipped_PathFilter(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("scan: %v\nstderr: %s", err, stderr)
	}

	entries := skippedJSON(t, fix, "--skipped-path", "generated/legacy.go")
	if len(entries) != 1 || jsonStr(entries[0]["rule"]) != "generated-dir" {
		t.Fatalf("--skipped-path generated/legacy.go = %v, want one generated-dir row", entries)
	}

	// A file that IS indexed is not on the ledger, and saying so is an
	// answer, not an error.
	stdout, _, err := runScanCmd(t, fix, "--skipped-path", "handwritten.go")
	if err != nil {
		t.Fatalf("--skipped-path handwritten.go: %v", err)
	}
	if !strings.Contains(stdout, "handwritten.go") {
		t.Errorf("output does not name the queried path:\n%s", stdout)
	}
}

// `atlas snapshot` ingests into the SAME database as `atlas scan`, so its
// ingest touches the shared exclusion ledger. It must not answer the
// operator's "why is this file not indexed?" with a walk they never ran:
// api/schema.pb.go is excluded by a configured glob, and a snapshot built
// from a different set of generated-code rules would quietly drop that row
// and leave --skipped reporting the file as never excluded.
func TestScanSkipped_SnapshotDoesNotRewriteTheLedger(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("scan: %v\nstderr: %s", err, stderr)
	}
	before := skippedByPath(t, fix)
	if _, ok := before["api/schema.pb.go"]; !ok {
		t.Fatalf("precondition: the scan did not record the glob exclusion: %v", before)
	}

	if _, stderr, err := runSnapshotCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("snapshot: %v\nstderr: %s", err, stderr)
	}

	after := skippedByPath(t, fix)
	pb, ok := after["api/schema.pb.go"]
	if !ok {
		t.Fatalf("the snapshot dropped api/schema.pb.go from the ledger; "+
			"--skipped now answers about the snapshot's configuration, not the "+
			"scan's: %v", after)
	}
	if got := jsonStr(pb["detail"]); got != "**/*.pb.go" {
		t.Errorf("api/schema.pb.go detail after snapshot = %q, want **/*.pb.go", got)
	}
	if len(after) != len(before) {
		t.Errorf("ledger changed size across a snapshot: %d → %d\nbefore %v\nafter %v",
			len(before), len(after), before, after)
	}
}

// Zero rows has two causes that mean opposite things. A database no scan has
// touched knows nothing about exclusions; reporting that as "the last scan
// excluded no files" turns an absence into a measurement.
func TestScanSkipped_NoLedgerIsNotAnEmptyLedger(t *testing.T) {
	fix := newSkippedFixture(t)

	stdout, _, err := runScanCmd(t, fix, "--skipped")
	if err != nil {
		t.Fatalf("scan --skipped on a fresh db: %v", err)
	}
	if strings.Contains(stdout, "excluded no files") {
		t.Errorf("a never-scanned database reports the last scan excluded "+
			"nothing:\n%s", stdout)
	}
	if !strings.Contains(stdout, "No exclusion ledger") {
		t.Errorf("output does not say the ledger is missing:\n%s", stdout)
	}
	if present := skippedEnvelope(t, fix, "--skipped").LedgerPresent; present {
		t.Error("ledger_present is true on a database that has never been scanned")
	}

	// Same query with --skipped-path must not claim the file is fine either.
	stdout, _, err = runScanCmd(t, fix, "--skipped-path", "generated/legacy.go")
	if err != nil {
		t.Fatalf("scan --skipped-path on a fresh db: %v", err)
	}
	if !strings.Contains(stdout, "Cannot determine") {
		t.Errorf("a fresh database answers a per-file query without saying it "+
			"cannot determine anything:\n%s", stdout)
	}

	// A scan that genuinely excludes nothing is the other cause, and it must
	// read differently.
	if _, stderr, err := runScanCmd(t, fix,
		"--root", generatedFixtureRoot, "--include-generated"); err != nil {
		t.Fatalf("scan --include-generated: %v\nstderr: %s", err, stderr)
	}
	stdout, _, err = runScanCmd(t, fix, "--skipped")
	if err != nil {
		t.Fatalf("scan --skipped after an empty scan: %v", err)
	}
	if !strings.Contains(stdout, "excluded no files") {
		t.Errorf("a scan that excluded nothing is not reported as such:\n%s", stdout)
	}
	if env := skippedEnvelope(t, fix, "--skipped"); !env.LedgerPresent {
		t.Error("ledger_present is false after a scan that recorded an empty ledger")
	}
}

// The ledger key is a project-relative slash path. The two spellings an
// operator actually types are neither: a shell tab-completed `./generated/…`
// and the absolute path an editor handed them. Both used to miss, and a miss
// used to read as "this file IS indexed".
func TestScanSkipped_PathSpellingsResolveToTheLedgerKey(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("scan: %v\nstderr: %s", err, stderr)
	}
	absRoot, err := filepath.Abs(generatedFixtureRoot)
	if err != nil {
		t.Fatalf("abs fixture root: %v", err)
	}

	for _, spelling := range []string{
		"./generated/legacy.go",
		"generated/./legacy.go",
		filepath.Join(absRoot, "generated", "legacy.go"),
	} {
		entries := skippedJSON(t, fix,
			"--root", generatedFixtureRoot, "--skipped-path", spelling)
		if len(entries) != 1 {
			t.Errorf("--skipped-path %q returned %d entries, want 1: the "+
				"lookup did not normalise the path to the ledger key",
				spelling, len(entries))
			continue
		}
		if got := jsonStr(entries[0]["rule"]); got != "generated-dir" {
			t.Errorf("--skipped-path %q rule = %q, want generated-dir", spelling, got)
		}
	}
}

// A path the ledger does not mention is not thereby indexed: it may have
// been outside the scan root, or deleted, or spelled for another tree. The
// ledger records exclusions and nothing else, and the output has to say so.
func TestScanSkipped_MissReportsAbsenceNotIndexing(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("scan: %v\nstderr: %s", err, stderr)
	}

	stdout, _, err := runScanCmd(t, fix,
		"--root", generatedFixtureRoot, "--skipped-path", "./handwritten.go")
	if err != nil {
		t.Fatalf("--skipped-path handwritten.go: %v", err)
	}
	if !strings.Contains(stdout, "not in the exclusion ledger") {
		t.Errorf("a miss is not reported as an absence from the ledger:\n%s", stdout)
	}
	// The normalised key, not the raw spelling, is what was looked up.
	if !strings.Contains(stdout, "handwritten.go") {
		t.Errorf("output does not name the path that was queried:\n%s", stdout)
	}
}

// `atlas init` writes the first ledger a database ever has, and the docs
// promise the detail column names the matching glob. Without the configured
// globs on the ingest, every glob-claimed file gets an empty detail —
// "generated-glob" with no pattern, which names no line of atlas.yaml and so
// tells the operator nothing they can act on.
func TestScanSkipped_InitRecordsTheMatchingGlob(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runInitCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("init: %v\nstderr: %s", err, stderr)
	}

	byPath := skippedByPath(t, fix)
	pb, ok := byPath["api/schema.pb.go"]
	if !ok {
		t.Fatalf("init recorded no ledger entry for api/schema.pb.go: %v", byPath)
	}
	if got := jsonStr(pb["detail"]); got != "**/*.pb.go" {
		t.Errorf("api/schema.pb.go detail after init = %q, want **/*.pb.go: the "+
			"ledger names the rule but not the config line behind it", got)
	}
}

// runInitCmd drives `atlas init` against the fixture DB.
func runInitCmd(t *testing.T, fix *skippedFixture, args ...string) (string, string, error) {
	t.Helper()
	root := NewRootCmd()
	var stdout, stderr bytes.Buffer
	root.SetOut(&stdout)
	root.SetErr(&stderr)
	root.SetArgs(append([]string{
		"init",
		"--db-path", fix.dbPath,
		"--config", fix.configPath,
	}, args...))
	err := root.ExecuteContext(context.Background())
	return stdout.String(), stderr.String(), err
}

// runSnapshotCmd drives `atlas snapshot` against the same fixture DB.
func runSnapshotCmd(t *testing.T, fix *skippedFixture, args ...string) (string, string, error) {
	t.Helper()
	root := NewRootCmd()
	var stdout, stderr bytes.Buffer
	root.SetOut(&stdout)
	root.SetErr(&stderr)
	root.SetArgs(append([]string{
		"snapshot",
		"--db-path", fix.dbPath,
		"--config", fix.configPath,
	}, args...))
	err := root.ExecuteContext(context.Background())
	return stdout.String(), stderr.String(), err
}

// skippedByPath reads the whole ledger back keyed by file_path.
func skippedByPath(t *testing.T, fix *skippedFixture) map[string]map[string]any {
	t.Helper()
	byPath := map[string]map[string]any{}
	for _, e := range skippedJSON(t, fix, "--skipped") {
		byPath[jsonStr(e["file_path"])] = e
	}
	return byPath
}

// skippedEnvelope exposes the fields of the result that are not rows.
type skippedResultJSON struct {
	LedgerPresent bool `json:"ledger_present"`
}

func skippedEnvelope(t *testing.T, fix *skippedFixture, args ...string) skippedResultJSON {
	t.Helper()
	stdout, stderr, err := runScanCmd(t, fix, append([]string{"--json"}, args...)...)
	if err != nil {
		t.Fatalf("scan --json %v: %v\nstderr: %s", args, err, stderr)
	}
	var env struct {
		Result skippedResultJSON `json:"result"`
	}
	if err := json.Unmarshal([]byte(stdout), &env); err != nil {
		t.Fatalf("unmarshal envelope: %v\n%s", err, stdout)
	}
	return env.Result
}

// skippedJSON runs the read path under --json and returns the entries.
func skippedJSON(t *testing.T, fix *skippedFixture, args ...string) []map[string]any {
	t.Helper()
	stdout, stderr, err := runScanCmd(t, fix, append([]string{"--json"}, args...)...)
	if err != nil {
		t.Fatalf("scan --json %v: %v\nstderr: %s", args, err, stderr)
	}
	var env struct {
		Result struct {
			Skipped []map[string]any `json:"skipped"`
		} `json:"result"`
	}
	if err := json.Unmarshal([]byte(stdout), &env); err != nil {
		t.Fatalf("unmarshal envelope: %v\n%s", err, stdout)
	}
	return env.Result.Skipped
}

func jsonStr(v any) string {
	s, _ := v.(string)
	return s
}
