package cli

import (
	"context"
	"testing"
)

// The generated-code rules (issue #96) are the scanner's, but they are only
// reachable if the CLI actually forwards them. This pins the wiring in both
// directions: scan.generated adds patterns, and --include-generated turns the
// exclusion off entirely.
//
// The fixture is the scanner's own generatedproject: handwritten.go is
// hand-written, and its siblings are generated by header, by directory, and
// (with the config below) by glob.
func TestIndexProjectFromConfig_GeneratedWiring(t *testing.T) {
	const root = "../../packages/codeindex/go/testdata/generatedproject"

	countSymbols := func(t *testing.T, cfg ScanConfig, includeGenerated bool) int {
		t.Helper()
		loaded = Config{repoRoot: root, Scan: cfg}
		idx, _, err := indexProjectFromConfig(context.Background(), root, false, nil, includeGenerated)
		if err != nil {
			t.Fatalf("indexProjectFromConfig: %v", err)
		}
		return len(idx.Symbols)
	}

	// Baseline: no extra patterns. schema.pb.go carries no "Code generated"
	// header and does not sit under a generated/ directory, so nothing but a
	// glob can exclude it.
	base := countSymbols(t, ScanConfig{}, false)
	globbed := countSymbols(t, ScanConfig{Generated: []string{"**/*.pb.go"}}, false)
	if globbed >= base {
		t.Errorf("scan.generated did not reach the scanner: %d symbols with the glob, %d without",
			globbed, base)
	}

	// --include-generated indexes everything the rules would have dropped.
	all := countSymbols(t, ScanConfig{Generated: []string{"**/*.pb.go"}}, true)
	if all <= base {
		t.Errorf("--include-generated did not reach the scanner: %d symbols, want more than the %d excluded baseline",
			all, base)
	}

	// The config form is equivalent to the flag: an operator who sets it in
	// atlas.yaml must not need to remember the flag as well.
	viaConfig := countSymbols(t, ScanConfig{
		Generated:        []string{"**/*.pb.go"},
		IncludeGenerated: true,
	}, false)
	if viaConfig != all {
		t.Errorf("scan.include_generated = %d symbols, --include-generated = %d; want the same", viaConfig, all)
	}
}
