package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// generatedFixtureRoot is the scanner's own generated-code fixture:
// handwritten.go is hand-written, and its siblings are generated by header
// (db/queries.sql.go, generated/with_header.go), by directory
// (generated/legacy.go) and — with the config written below — by glob
// (api/schema.pb.go).
const generatedFixtureRoot = "../../packages/codeindex/go/testdata/generatedproject"

// skippedFixture is a temp DB plus a config that turns two of the fixture's
// files into glob matches. Both globs deliberately overlap a rule that is
// stronger than they are, so the ledger has something to get wrong.
type skippedFixture struct {
	dbPath     string
	configPath string
}

func newSkippedFixture(t *testing.T) *skippedFixture {
	t.Helper()
	dir := t.TempDir()
	cfg := filepath.Join(dir, "atlas.yaml")
	const body = `scan:
  generated:
    - "**/*.pb.go"
    - "**/*.sql.go"
`
	if err := os.WriteFile(cfg, []byte(body), 0o600); err != nil {
		t.Fatalf("write config: %v", err)
	}
	return &skippedFixture{dbPath: filepath.Join(dir, "atlas.db"), configPath: cfg}
}

func runScanCmd(t *testing.T, fix *skippedFixture, args ...string) (string, string, error) {
	t.Helper()
	root := NewRootCmd()
	var stdout, stderr bytes.Buffer
	root.SetOut(&stdout)
	root.SetErr(&stderr)
	root.SetArgs(append([]string{
		"scan",
		"--db-path", fix.dbPath,
		"--config", fix.configPath,
	}, args...))
	err := root.ExecuteContext(context.Background())
	return stdout.String(), stderr.String(), err
}

// The point of the ledger: after the scan that dropped a file has scrolled
// out of the terminal, the store still knows which rule dropped it.
func TestScanSkipped_ReadsTheLedgerBackWithoutRescanning(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("scan: %v\nstderr: %s", err, stderr)
	}

	stdout, stderr, err := runScanCmd(t, fix, "--skipped")
	if err != nil {
		t.Fatalf("scan --skipped: %v\nstderr: %s", err, stderr)
	}
	for _, want := range []string{
		"api/schema.pb.go", "generated-glob", "**/*.pb.go",
		"db/queries.sql.go", "generated-header",
		"generated/legacy.go", "generated-dir",
	} {
		if !strings.Contains(stdout, want) {
			t.Errorf("scan --skipped output missing %q:\n%s", want, stdout)
		}
	}
	// The read path must not walk the tree again — a scan summary line here
	// would mean the answer came from a fresh scan, not from the store.
	if strings.Contains(stdout, "files_scanned=") {
		t.Errorf("scan --skipped re-ran the scan:\n%s", stdout)
	}
}

// The rule recorded must be the one that CLAIMED the file. queries.sql.go
// carries the generated header AND matches `**/*.sql.go`; the scanner checks
// the header first (issue #96), and this ledger is the only place that
// ordering leaves a trace.
func TestScanSkipped_TwoRulesRecordTheClaimingRule(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("scan: %v\nstderr: %s", err, stderr)
	}

	entries := skippedJSON(t, fix, "--skipped")
	byPath := map[string]map[string]any{}
	for _, e := range entries {
		byPath[jsonStr(e["file_path"])] = e
	}

	sqlgo, ok := byPath["db/queries.sql.go"]
	if !ok {
		t.Fatalf("db/queries.sql.go missing from the ledger: %v", byPath)
	}
	if got := jsonStr(sqlgo["rule"]); got != "generated-header" {
		t.Errorf("db/queries.sql.go rule = %q, want generated-header "+
			"(the header rule claimed it; the glob only also matched)", got)
	}
	if got := jsonStr(sqlgo["detail"]); got != "" {
		t.Errorf("db/queries.sql.go detail = %q, want empty: naming the glob "+
			"would send the operator to a config line whose removal changes nothing", got)
	}

	// generated/with_header.go matches the header rule and the directory
	// rule. Same principle, the other pair.
	withHeader, ok := byPath["generated/with_header.go"]
	if !ok {
		t.Fatalf("generated/with_header.go missing from the ledger: %v", byPath)
	}
	if got := jsonStr(withHeader["rule"]); got != "generated-header" {
		t.Errorf("generated/with_header.go rule = %q, want generated-header", got)
	}

	// And the glob case names the pattern, which is the whole reason the
	// reason is not just "generated".
	pb, ok := byPath["api/schema.pb.go"]
	if !ok {
		t.Fatalf("api/schema.pb.go missing from the ledger: %v", byPath)
	}
	if got := jsonStr(pb["rule"]); got != "generated-glob" {
		t.Errorf("api/schema.pb.go rule = %q, want generated-glob", got)
	}
	if got := jsonStr(pb["detail"]); got != "**/*.pb.go" {
		t.Errorf("api/schema.pb.go detail = %q, want **/*.pb.go", got)
	}
}

// A file that stops being skipped must leave the ledger, or the ledger
// becomes a record of every rule ever tried.
func TestScanSkipped_ReplacedNotAppended(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("first scan: %v\nstderr: %s", err, stderr)
	}
	if n := len(skippedJSON(t, fix, "--skipped")); n == 0 {
		t.Fatal("first scan recorded nothing")
	}

	if _, stderr, err := runScanCmd(t, fix,
		"--root", generatedFixtureRoot, "--include-generated"); err != nil {
		t.Fatalf("second scan: %v\nstderr: %s", err, stderr)
	}
	if entries := skippedJSON(t, fix, "--skipped"); len(entries) != 0 {
		t.Fatalf("ledger after --include-generated = %v, want empty", entries)
	}
}

// One-file lookup: the question an operator actually asks.
func TestScanSkipped_PathFilter(t *testing.T) {
	fix := newSkippedFixture(t)
	if _, stderr, err := runScanCmd(t, fix, "--root", generatedFixtureRoot); err != nil {
		t.Fatalf("scan: %v\nstderr: %s", err, stderr)
	}

	entries := skippedJSON(t, fix, "--skipped-path", "generated/legacy.go")
	if len(entries) != 1 || jsonStr(entries[0]["rule"]) != "generated-dir" {
		t.Fatalf("--skipped-path generated/legacy.go = %v, want one generated-dir row", entries)
	}

	// A file that IS indexed is not on the ledger, and saying so is an
	// answer, not an error.
	stdout, _, err := runScanCmd(t, fix, "--skipped-path", "handwritten.go")
	if err != nil {
		t.Fatalf("--skipped-path handwritten.go: %v", err)
	}
	if !strings.Contains(stdout, "handwritten.go") {
		t.Errorf("output does not name the queried path:\n%s", stdout)
	}
}

// skippedJSON runs the read path under --json and returns the entries.
func skippedJSON(t *testing.T, fix *skippedFixture, args ...string) []map[string]any {
	t.Helper()
	stdout, stderr, err := runScanCmd(t, fix, append([]string{"--json"}, args...)...)
	if err != nil {
		t.Fatalf("scan --json %v: %v\nstderr: %s", args, err, stderr)
	}
	var env struct {
		Result struct {
			Skipped []map[string]any `json:"skipped"`
		} `json:"result"`
	}
	if err := json.Unmarshal([]byte(stdout), &env); err != nil {
		t.Fatalf("unmarshal envelope: %v\n%s", err, stdout)
	}
	return env.Result.Skipped
}

func jsonStr(v any) string {
	s, _ := v.(string)
	return s
}
