// Code generated by a fixture. DO NOT EDIT.

package sink

// Buffered is the second implementation of Writer. The header above puts
// this file in the exclusion ledger, so the scan never indexes
// Buffered.Write -- while go/packages type-checks it like any other file
// and CHA counts it as a candidate at every Writer.Write call site.
type Buffered struct{ n int }

// Write records s.
func (b *Buffered) Write(s string) int {
	b.n += len(s)
	return b.n
}
