// Package store is Atlas's SQLite-backed registry + cache.
//
// It is the ONLY package in Atlas allowed to import database/sql and a
// SQLite driver (modernc.org/sqlite, pure-Go). Per docs/architecture.md
// §3.7, schema lives under store/schema/NNNN_*.up.sql and is embedded into
// the binary via //go:embed. Migrations are one-way (no .down.sql files —
// the per-developer cache DB is re-derivable; `rm atlas-state.db &&
// atlas init` is the canonical rollback path).
//
// Migrations are applied by golang-migrate (v4) via its iofs source and
// the modernc-backed sqlite driver. The migration runner records its
// state in the default `schema_migrations` table — Atlas never writes to
// that table itself.
//
// Per-table SQL queries are generated by sqlc (engine: sqlite, driver:
// modernc.org/sqlite). Generated code lives under packages/store/sqlc/
// and is committed alongside the queries it derives from. Hand-written
// narrow ports in this package wrap the generated *sqlc.Queries type so
// the public API surface (Features, Symbols, Edges, …) stays domain-typed
// while the SQL stays declarative.
//
// The package's external surface is a *Store handle plus a set of narrow
// "port" interfaces (Features, Symbols, Edges, FeatureSymbols, FileHashes,
// Coverage, AuditSnapshots, Annotations, Config). Each port is satisfied
// by a sqlite-backed implementation in this package; external consumers
// depend on the interfaces.
//
// Schema reference: docs/schema-v1.md.
package store
