// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations.sql

package sqlc

import (
	"context"
)

const deleteAnnotationsByFile = `-- name: DeleteAnnotationsByFile :exec
DELETE FROM annotations WHERE file_path = ?
`

func (q *Queries) DeleteAnnotationsByFile(ctx context.Context, filePath string) error {
	_, err := q.db.ExecContext(ctx, deleteAnnotationsByFile, filePath)
	return err
}

const listAnnotationsByFile = `-- name: ListAnnotationsByFile :many
SELECT id, file_path, line, kind, value, source, parsed_at
FROM annotations
WHERE file_path = ?
ORDER BY line, kind
`

func (q *Queries) ListAnnotationsByFile(ctx context.Context, filePath string) ([]Annotation, error) {
	rows, err := q.db.QueryContext(ctx, listAnnotationsByFile, filePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Annotation{}
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.Line,
			&i.Kind,
			&i.Value,
			&i.Source,
			&i.ParsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnnotation = `-- name: UpsertAnnotation :exec
INSERT INTO annotations (file_path, line, kind, value, source)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(file_path, line, kind) DO UPDATE SET
  value     = excluded.value,
  source    = excluded.source,
  parsed_at = CURRENT_TIMESTAMP
`

type UpsertAnnotationParams struct {
	FilePath string `db:"file_path" json:"file_path"`
	Line     int64  `db:"line" json:"line"`
	Kind     string `db:"kind" json:"kind"`
	Value    string `db:"value" json:"value"`
	Source   string `db:"source" json:"source"`
}

func (q *Queries) UpsertAnnotation(ctx context.Context, arg UpsertAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnnotation,
		arg.FilePath,
		arg.Line,
		arg.Kind,
		arg.Value,
		arg.Source,
	)
	return err
}
