// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carryforward.sql

package sqlc

import (
	"context"
	"time"
)

const listCarrySources = `-- name: ListCarrySources :many

SELECT
  r.symbol_id          AS symbol_id,
  MAX(g.finished_at)   AS measured_at,
  g.id                 AS run_id,
  g.run_group          AS run_group,
  r.feature_id         AS feature_id,
  sp.file_path         AS span_file_path,
  sp.line              AS span_line,
  sp.end_line          AS span_end_line,
  y.file_path          AS current_file_path,
  y.line               AS current_line,
  y.end_line           AS current_end_line
FROM coverage_results r
JOIN coverage_runs g ON g.id = r.run_id
JOIN symbols y ON y.id = r.symbol_id
LEFT JOIN coverage_symbol_spans sp
  ON sp.run_id = r.run_id AND sp.symbol_id = r.symbol_id
WHERE r.symbol_id IS NOT NULL
  AND g.run_group IS NOT NULL
  AND g.run_group <> ?1
  AND g.finished_at <= ?2
  AND g.finished_at >= ?3
GROUP BY r.symbol_id
`

type ListCarrySourcesParams struct {
	CurrentGroup *string   `db:"current_group" json:"current_group"`
	FrontierAt   time.Time `db:"frontier_at" json:"frontier_at"`
	HorizonAt    time.Time `db:"horizon_at" json:"horizon_at"`
}

type ListCarrySourcesRow struct {
	SymbolID        *int64      `db:"symbol_id" json:"symbol_id"`
	MeasuredAt      interface{} `db:"measured_at" json:"measured_at"`
	RunID           int64       `db:"run_id" json:"run_id"`
	RunGroup        *string     `db:"run_group" json:"run_group"`
	FeatureID       *string     `db:"feature_id" json:"feature_id"`
	SpanFilePath    *string     `db:"span_file_path" json:"span_file_path"`
	SpanLine        *int64      `db:"span_line" json:"span_line"`
	SpanEndLine     *int64      `db:"span_end_line" json:"span_end_line"`
	CurrentFilePath string      `db:"current_file_path" json:"current_file_path"`
	CurrentLine     int64       `db:"current_line" json:"current_line"`
	CurrentEndLine  *int64      `db:"current_end_line" json:"current_end_line"`
}

// Carryforward reads (issue #136). All three queries share one window:
// grouped runs only, finished at or before the current frontier, and no older
// than the lookback horizon. Ungrouped runs are excluded on purpose -- a run
// group is the operator's declaration that a set of syncs is ONE build, and
// without it "the previous build" has no meaning, so an ungrouped store keeps
// its pre-#136 behaviour exactly.
// The newest prior measurement of each symbol, with the span recorded when it
// was taken (schema 0017) alongside the symbol's span today.
//
// SQLite defines the bare columns of a query carrying a single max() to come
// from the row that produced the maximum, so this resolves "which build last
// measured this symbol" in one grouped read rather than one query per
// candidate build. The per-run statement totals are NOT read here: a symbol
// can own several result rows in one run, and picking one of them would
// under-count. ListCarrySymbolTotals sums them.
func (q *Queries) ListCarrySources(ctx context.Context, arg ListCarrySourcesParams) ([]ListCarrySourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCarrySources, arg.CurrentGroup, arg.FrontierAt, arg.HorizonAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarrySourcesRow{}
	for rows.Next() {
		var i ListCarrySourcesRow
		if err := rows.Scan(
			&i.SymbolID,
			&i.MeasuredAt,
			&i.RunID,
			&i.RunGroup,
			&i.FeatureID,
			&i.SpanFilePath,
			&i.SpanLine,
			&i.SpanEndLine,
			&i.CurrentFilePath,
			&i.CurrentLine,
			&i.CurrentEndLine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarrySymbolTotals = `-- name: ListCarrySymbolTotals :many
SELECT
  r.run_id                                          AS run_id,
  r.symbol_id                                       AS symbol_id,
  CAST(SUM(r.covered_stmts) AS INTEGER)             AS covered_stmts,
  CAST(SUM(r.total_stmts) AS INTEGER)               AS total_stmts,
  CAST(MAX(CASE WHEN r.status = 'pass' THEN 1 ELSE 0 END) AS INTEGER) AS any_pass,
  CAST(MAX(CASE WHEN r.status = 'skip' THEN 1 ELSE 0 END) AS INTEGER) AS any_skip
FROM coverage_results r
JOIN coverage_runs g ON g.id = r.run_id
WHERE r.symbol_id IS NOT NULL
  AND g.run_group IS NOT NULL
  AND g.run_group <> ?1
  AND g.finished_at <= ?2
  AND g.finished_at >= ?3
GROUP BY r.run_id, r.symbol_id
`

type ListCarrySymbolTotalsParams struct {
	CurrentGroup *string   `db:"current_group" json:"current_group"`
	FrontierAt   time.Time `db:"frontier_at" json:"frontier_at"`
	HorizonAt    time.Time `db:"horizon_at" json:"horizon_at"`
}

type ListCarrySymbolTotalsRow struct {
	RunID        int64  `db:"run_id" json:"run_id"`
	SymbolID     *int64 `db:"symbol_id" json:"symbol_id"`
	CoveredStmts int64  `db:"covered_stmts" json:"covered_stmts"`
	TotalStmts   int64  `db:"total_stmts" json:"total_stmts"`
	AnyPass      int64  `db:"any_pass" json:"any_pass"`
	AnySkip      int64  `db:"any_skip" json:"any_skip"`
}

// Per (run, symbol) statement totals and status rollup over the same window.
// Summing is what classifyCoverageResults does when it pools a live frontier,
// so a carried reading is assembled the same way the observed one is.
func (q *Queries) ListCarrySymbolTotals(ctx context.Context, arg ListCarrySymbolTotalsParams) ([]ListCarrySymbolTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCarrySymbolTotals, arg.CurrentGroup, arg.FrontierAt, arg.HorizonAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCarrySymbolTotalsRow{}
	for rows.Next() {
		var i ListCarrySymbolTotalsRow
		if err := rows.Scan(
			&i.RunID,
			&i.SymbolID,
			&i.CoveredStmts,
			&i.TotalStmts,
			&i.AnyPass,
			&i.AnySkip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRunGroups = `-- name: ListRecentRunGroups :many
SELECT g.run_group AS run_group
FROM coverage_runs g
WHERE g.run_group IS NOT NULL
  AND g.finished_at <= ?1
GROUP BY g.run_group
ORDER BY MAX(g.finished_at) DESC
LIMIT ?2
`

type ListRecentRunGroupsParams struct {
	FrontierAt time.Time `db:"frontier_at" json:"frontier_at"`
	MaxGroups  int64     `db:"max_groups" json:"max_groups"`
}

// The most recent grouped frontiers, newest first, so a carry can be measured
// in BUILDS rather than in wall clock alone. The caller passes a limit of
// (window + 1) frontiers: a source group that does not appear in the answer is
// by construction further back than the window allows.
func (q *Queries) ListRecentRunGroups(ctx context.Context, arg ListRecentRunGroupsParams) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRunGroups, arg.FrontierAt, arg.MaxGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var run_group *string
		if err := rows.Scan(&run_group); err != nil {
			return nil, err
		}
		items = append(items, run_group)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
