// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package sqlc

import (
	"context"
)

const deleteConfig = `-- name: DeleteConfig :exec
DELETE FROM config WHERE key = ?
`

func (q *Queries) DeleteConfig(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteConfig, key)
	return err
}

const getConfig = `-- name: GetConfig :one
SELECT value FROM config WHERE key = ?
`

func (q *Queries) GetConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listConfig = `-- name: ListConfig :many
SELECT key, value, updated_at FROM config ORDER BY key
`

func (q *Queries) ListConfig(ctx context.Context) ([]Config, error) {
	rows, err := q.db.QueryContext(ctx, listConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Config{}
	for rows.Next() {
		var i Config
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConfig = `-- name: SetConfig :exec
INSERT INTO config (key, value, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(key) DO UPDATE SET
  value      = excluded.value,
  updated_at = CURRENT_TIMESTAMP
`

type SetConfigParams struct {
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConfig, arg.Key, arg.Value)
	return err
}
