// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: controlflow.sql

package sqlc

import (
	"context"
)

const deleteCFGBlocks = `-- name: DeleteCFGBlocks :exec

DELETE FROM cfg_blocks WHERE symbol_id = ?
`

// Control-flow queries (migration 0015, issue #127).
//
// Every statement here is per-symbol by design: a flow result that does not
// carry the symbol it belongs to cannot be joined back to the graph, and an
// analysis nobody can join is an analysis nobody uses.
//
// Writes are all INSERT OR REPLACE and the port clears a symbol's rows before
// rewriting them, so re-running the builder over an unchanged file is a no-op
// and re-running it over a changed one cannot leave two generations of blocks
// interleaved.
func (q *Queries) DeleteCFGBlocks(ctx context.Context, symbolID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCFGBlocks, symbolID)
	return err
}

const deleteCFGDecisionCoverage = `-- name: DeleteCFGDecisionCoverage :exec
DELETE FROM cfg_decision_coverage WHERE symbol_id = ?
`

func (q *Queries) DeleteCFGDecisionCoverage(ctx context.Context, symbolID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCFGDecisionCoverage, symbolID)
	return err
}

const deleteCFGEdges = `-- name: DeleteCFGEdges :exec
DELETE FROM cfg_edges WHERE symbol_id = ?
`

func (q *Queries) DeleteCFGEdges(ctx context.Context, symbolID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCFGEdges, symbolID)
	return err
}

const deleteCFGFindings = `-- name: DeleteCFGFindings :exec
DELETE FROM cfg_findings WHERE symbol_id = ?
`

func (q *Queries) DeleteCFGFindings(ctx context.Context, symbolID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCFGFindings, symbolID)
	return err
}

const getCFGDecisionCoverage = `-- name: GetCFGDecisionCoverage :one
SELECT symbol_id, outcomes_total, outcomes_decidable, outcomes_taken, source, measured_at
FROM cfg_decision_coverage
WHERE symbol_id = ?
`

func (q *Queries) GetCFGDecisionCoverage(ctx context.Context, symbolID int64) (CfgDecisionCoverage, error) {
	row := q.db.QueryRowContext(ctx, getCFGDecisionCoverage, symbolID)
	var i CfgDecisionCoverage
	err := row.Scan(
		&i.SymbolID,
		&i.OutcomesTotal,
		&i.OutcomesDecidable,
		&i.OutcomesTaken,
		&i.Source,
		&i.MeasuredAt,
	)
	return i, err
}

const getCFGSymbol = `-- name: GetCFGSymbol :one
SELECT symbol_id, complexity, decisions, branch_arms,
       conditions, conditions_independent, defers, unreachable_blocks, built_at
FROM cfg_symbols
WHERE symbol_id = ?
`

func (q *Queries) GetCFGSymbol(ctx context.Context, symbolID int64) (CfgSymbol, error) {
	row := q.db.QueryRowContext(ctx, getCFGSymbol, symbolID)
	var i CfgSymbol
	err := row.Scan(
		&i.SymbolID,
		&i.Complexity,
		&i.Decisions,
		&i.BranchArms,
		&i.Conditions,
		&i.ConditionsIndependent,
		&i.Defers,
		&i.UnreachableBlocks,
		&i.BuiltAt,
	)
	return i, err
}

const insertCFGBlock = `-- name: InsertCFGBlock :exec
INSERT OR REPLACE INTO cfg_blocks (symbol_id, block_index, kind, start_line, end_line)
VALUES (?, ?, ?, ?, ?)
`

type InsertCFGBlockParams struct {
	SymbolID   int64  `db:"symbol_id" json:"symbol_id"`
	BlockIndex int64  `db:"block_index" json:"block_index"`
	Kind       string `db:"kind" json:"kind"`
	StartLine  int64  `db:"start_line" json:"start_line"`
	EndLine    int64  `db:"end_line" json:"end_line"`
}

func (q *Queries) InsertCFGBlock(ctx context.Context, arg InsertCFGBlockParams) error {
	_, err := q.db.ExecContext(ctx, insertCFGBlock,
		arg.SymbolID,
		arg.BlockIndex,
		arg.Kind,
		arg.StartLine,
		arg.EndLine,
	)
	return err
}

const insertCFGEdge = `-- name: InsertCFGEdge :exec
INSERT OR REPLACE INTO cfg_edges (symbol_id, edge_index, from_block, to_block, kind, condition)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCFGEdgeParams struct {
	SymbolID  int64  `db:"symbol_id" json:"symbol_id"`
	EdgeIndex int64  `db:"edge_index" json:"edge_index"`
	FromBlock int64  `db:"from_block" json:"from_block"`
	ToBlock   int64  `db:"to_block" json:"to_block"`
	Kind      string `db:"kind" json:"kind"`
	Condition string `db:"condition" json:"condition"`
}

func (q *Queries) InsertCFGEdge(ctx context.Context, arg InsertCFGEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertCFGEdge,
		arg.SymbolID,
		arg.EdgeIndex,
		arg.FromBlock,
		arg.ToBlock,
		arg.Kind,
		arg.Condition,
	)
	return err
}

const insertCFGFinding = `-- name: InsertCFGFinding :exec
INSERT OR REPLACE INTO cfg_findings (
  symbol_id, finding_index, kind, confidence, line, related_line, detail
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertCFGFindingParams struct {
	SymbolID     int64  `db:"symbol_id" json:"symbol_id"`
	FindingIndex int64  `db:"finding_index" json:"finding_index"`
	Kind         string `db:"kind" json:"kind"`
	Confidence   string `db:"confidence" json:"confidence"`
	Line         int64  `db:"line" json:"line"`
	RelatedLine  int64  `db:"related_line" json:"related_line"`
	Detail       string `db:"detail" json:"detail"`
}

func (q *Queries) InsertCFGFinding(ctx context.Context, arg InsertCFGFindingParams) error {
	_, err := q.db.ExecContext(ctx, insertCFGFinding,
		arg.SymbolID,
		arg.FindingIndex,
		arg.Kind,
		arg.Confidence,
		arg.Line,
		arg.RelatedLine,
		arg.Detail,
	)
	return err
}

const listAllCFGFindings = `-- name: ListAllCFGFindings :many
SELECT symbol_id, finding_index, kind, confidence, line, related_line, detail
FROM cfg_findings
ORDER BY CASE confidence WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END,
         kind, symbol_id, finding_index
`

func (q *Queries) ListAllCFGFindings(ctx context.Context) ([]CfgFinding, error) {
	rows, err := q.db.QueryContext(ctx, listAllCFGFindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CfgFinding{}
	for rows.Next() {
		var i CfgFinding
		if err := rows.Scan(
			&i.SymbolID,
			&i.FindingIndex,
			&i.Kind,
			&i.Confidence,
			&i.Line,
			&i.RelatedLine,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCFGBlocks = `-- name: ListCFGBlocks :many
SELECT symbol_id, block_index, kind, start_line, end_line
FROM cfg_blocks
WHERE symbol_id = ?
ORDER BY block_index
`

func (q *Queries) ListCFGBlocks(ctx context.Context, symbolID int64) ([]CfgBlock, error) {
	rows, err := q.db.QueryContext(ctx, listCFGBlocks, symbolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CfgBlock{}
	for rows.Next() {
		var i CfgBlock
		if err := rows.Scan(
			&i.SymbolID,
			&i.BlockIndex,
			&i.Kind,
			&i.StartLine,
			&i.EndLine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCFGEdges = `-- name: ListCFGEdges :many
SELECT symbol_id, edge_index, from_block, to_block, kind, condition
FROM cfg_edges
WHERE symbol_id = ?
ORDER BY edge_index
`

func (q *Queries) ListCFGEdges(ctx context.Context, symbolID int64) ([]CfgEdge, error) {
	rows, err := q.db.QueryContext(ctx, listCFGEdges, symbolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CfgEdge{}
	for rows.Next() {
		var i CfgEdge
		if err := rows.Scan(
			&i.SymbolID,
			&i.EdgeIndex,
			&i.FromBlock,
			&i.ToBlock,
			&i.Kind,
			&i.Condition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCFGFindingsByKind = `-- name: ListCFGFindingsByKind :many
SELECT symbol_id, finding_index, kind, confidence, line, related_line, detail
FROM cfg_findings
WHERE kind = ?
ORDER BY CASE confidence WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END,
         symbol_id, finding_index
`

// Highest confidence first so a consumer reading only the head of the list
// sees the findings most likely to be real.
func (q *Queries) ListCFGFindingsByKind(ctx context.Context, kind string) ([]CfgFinding, error) {
	rows, err := q.db.QueryContext(ctx, listCFGFindingsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CfgFinding{}
	for rows.Next() {
		var i CfgFinding
		if err := rows.Scan(
			&i.SymbolID,
			&i.FindingIndex,
			&i.Kind,
			&i.Confidence,
			&i.Line,
			&i.RelatedLine,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCFGFindingsBySymbol = `-- name: ListCFGFindingsBySymbol :many
SELECT symbol_id, finding_index, kind, confidence, line, related_line, detail
FROM cfg_findings
WHERE symbol_id = ?
ORDER BY finding_index
`

func (q *Queries) ListCFGFindingsBySymbol(ctx context.Context, symbolID int64) ([]CfgFinding, error) {
	rows, err := q.db.QueryContext(ctx, listCFGFindingsBySymbol, symbolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CfgFinding{}
	for rows.Next() {
		var i CfgFinding
		if err := rows.Scan(
			&i.SymbolID,
			&i.FindingIndex,
			&i.Kind,
			&i.Confidence,
			&i.Line,
			&i.RelatedLine,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCFGSymbolsByComplexity = `-- name: ListCFGSymbolsByComplexity :many
SELECT symbol_id, complexity, decisions, branch_arms,
       conditions, conditions_independent, defers, unreachable_blocks, built_at
FROM cfg_symbols
ORDER BY complexity DESC, symbol_id ASC
LIMIT ?
`

// Most complex first: the order the hotspot ranking wants. Ties break by
// symbol_id so a paged read is stable across calls.
func (q *Queries) ListCFGSymbolsByComplexity(ctx context.Context, limit int64) ([]CfgSymbol, error) {
	rows, err := q.db.QueryContext(ctx, listCFGSymbolsByComplexity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CfgSymbol{}
	for rows.Next() {
		var i CfgSymbol
		if err := rows.Scan(
			&i.SymbolID,
			&i.Complexity,
			&i.Decisions,
			&i.BranchArms,
			&i.Conditions,
			&i.ConditionsIndependent,
			&i.Defers,
			&i.UnreachableBlocks,
			&i.BuiltAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCFGDecisionCoverage = `-- name: UpsertCFGDecisionCoverage :exec
INSERT OR REPLACE INTO cfg_decision_coverage (
  symbol_id, outcomes_total, outcomes_decidable, outcomes_taken, source, measured_at
) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
`

type UpsertCFGDecisionCoverageParams struct {
	SymbolID          int64  `db:"symbol_id" json:"symbol_id"`
	OutcomesTotal     int64  `db:"outcomes_total" json:"outcomes_total"`
	OutcomesDecidable int64  `db:"outcomes_decidable" json:"outcomes_decidable"`
	OutcomesTaken     int64  `db:"outcomes_taken" json:"outcomes_taken"`
	Source            string `db:"source" json:"source"`
}

// outcomes_decidable is the denominator; outcomes_total is NOT. The gap
// between them is the part of the branching no statement-coverage profile can
// judge, and it is stored so a reader can report it instead of dividing it
// away.
func (q *Queries) UpsertCFGDecisionCoverage(ctx context.Context, arg UpsertCFGDecisionCoverageParams) error {
	_, err := q.db.ExecContext(ctx, upsertCFGDecisionCoverage,
		arg.SymbolID,
		arg.OutcomesTotal,
		arg.OutcomesDecidable,
		arg.OutcomesTaken,
		arg.Source,
	)
	return err
}

const upsertCFGSymbol = `-- name: UpsertCFGSymbol :exec
INSERT OR REPLACE INTO cfg_symbols (
  symbol_id, complexity, decisions, branch_arms,
  conditions, conditions_independent, defers, unreachable_blocks, built_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
`

type UpsertCFGSymbolParams struct {
	SymbolID              int64 `db:"symbol_id" json:"symbol_id"`
	Complexity            int64 `db:"complexity" json:"complexity"`
	Decisions             int64 `db:"decisions" json:"decisions"`
	BranchArms            int64 `db:"branch_arms" json:"branch_arms"`
	Conditions            int64 `db:"conditions" json:"conditions"`
	ConditionsIndependent int64 `db:"conditions_independent" json:"conditions_independent"`
	Defers                int64 `db:"defers" json:"defers"`
	UnreachableBlocks     int64 `db:"unreachable_blocks" json:"unreachable_blocks"`
}

func (q *Queries) UpsertCFGSymbol(ctx context.Context, arg UpsertCFGSymbolParams) error {
	_, err := q.db.ExecContext(ctx, upsertCFGSymbol,
		arg.SymbolID,
		arg.Complexity,
		arg.Decisions,
		arg.BranchArms,
		arg.Conditions,
		arg.ConditionsIndependent,
		arg.Defers,
		arg.UnreachableBlocks,
	)
	return err
}
