// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coverage_gaps.sql

package sqlc

import (
	"context"
)

const deleteCoverageRunGaps = `-- name: DeleteCoverageRunGaps :exec
DELETE FROM coverage_run_gaps WHERE run_id = ?
`

// Clears a run's list before rewriting it, so a re-ingest cannot leave two
// generations of rows interleaved.
func (q *Queries) DeleteCoverageRunGaps(ctx context.Context, runID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCoverageRunGaps, runID)
	return err
}

const insertCoverageRunGap = `-- name: InsertCoverageRunGap :exec
INSERT OR REPLACE INTO coverage_run_gaps (run_id, path, stmts, reason)
VALUES (?, ?, ?, ?)
`

type InsertCoverageRunGapParams struct {
	RunID  int64  `db:"run_id" json:"run_id"`
	Path   string `db:"path" json:"path"`
	Stmts  int64  `db:"stmts" json:"stmts"`
	Reason string `db:"reason" json:"reason"`
}

// One row per file whose execution could not be charged to a symbol.
// REPLACE so a retried ingest of the same run is idempotent.
func (q *Queries) InsertCoverageRunGap(ctx context.Context, arg InsertCoverageRunGapParams) error {
	_, err := q.db.ExecContext(ctx, insertCoverageRunGap,
		arg.RunID,
		arg.Path,
		arg.Stmts,
		arg.Reason,
	)
	return err
}

const listCoverageRunGaps = `-- name: ListCoverageRunGaps :many
SELECT path, stmts, reason
FROM coverage_run_gaps
WHERE run_id = ?
ORDER BY stmts DESC, path ASC
`

type ListCoverageRunGapsRow struct {
	Path   string `db:"path" json:"path"`
	Stmts  int64  `db:"stmts" json:"stmts"`
	Reason string `db:"reason" json:"reason"`
}

// Biggest loss first, ties broken by path: a consumer reading only the head
// of the list still sees the worst offenders, in a stable order.
func (q *Queries) ListCoverageRunGaps(ctx context.Context, runID int64) ([]ListCoverageRunGapsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoverageRunGaps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoverageRunGapsRow{}
	for rows.Next() {
		var i ListCoverageRunGapsRow
		if err := rows.Scan(&i.Path, &i.Stmts, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCoverageRunGapsTruncated = `-- name: SetCoverageRunGapsTruncated :exec
UPDATE coverage_runs SET gaps_truncated = ? WHERE id = ?
`

type SetCoverageRunGapsTruncatedParams struct {
	GapsTruncated int64 `db:"gaps_truncated" json:"gaps_truncated"`
	ID            int64 `db:"id" json:"id"`
}

// Records how many gap files did not fit the per-run cap. Written in the same
// transaction as the rows themselves, so the count and the list can never
// disagree about whether the list is complete.
func (q *Queries) SetCoverageRunGapsTruncated(ctx context.Context, arg SetCoverageRunGapsTruncatedParams) error {
	_, err := q.db.ExecContext(ctx, setCoverageRunGapsTruncated, arg.GapsTruncated, arg.ID)
	return err
}
