// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coverage.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getCoverageRun = `-- name: GetCoverageRun :one
SELECT id, framework, started_at, finished_at, raw_path, summary_json
FROM coverage_runs
WHERE id = ?
`

func (q *Queries) GetCoverageRun(ctx context.Context, id int64) (CoverageRun, error) {
	row := q.db.QueryRowContext(ctx, getCoverageRun, id)
	var i CoverageRun
	err := row.Scan(
		&i.ID,
		&i.Framework,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RawPath,
		&i.SummaryJson,
	)
	return i, err
}

const insertCoverageResult = `-- name: InsertCoverageResult :exec
INSERT INTO coverage_results (run_id, symbol_id, feature_id, status, duration_ms, message)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCoverageResultParams struct {
	RunID      int64   `db:"run_id" json:"run_id"`
	SymbolID   *int64  `db:"symbol_id" json:"symbol_id"`
	FeatureID  *string `db:"feature_id" json:"feature_id"`
	Status     string  `db:"status" json:"status"`
	DurationMs int64   `db:"duration_ms" json:"duration_ms"`
	Message    *string `db:"message" json:"message"`
}

func (q *Queries) InsertCoverageResult(ctx context.Context, arg InsertCoverageResultParams) error {
	_, err := q.db.ExecContext(ctx, insertCoverageResult,
		arg.RunID,
		arg.SymbolID,
		arg.FeatureID,
		arg.Status,
		arg.DurationMs,
		arg.Message,
	)
	return err
}

const insertCoverageRun = `-- name: InsertCoverageRun :execresult
INSERT INTO coverage_runs (framework, started_at, finished_at, raw_path, summary_json)
VALUES (?, ?, ?, ?, ?)
`

type InsertCoverageRunParams struct {
	Framework   string    `db:"framework" json:"framework"`
	StartedAt   time.Time `db:"started_at" json:"started_at"`
	FinishedAt  time.Time `db:"finished_at" json:"finished_at"`
	RawPath     *string   `db:"raw_path" json:"raw_path"`
	SummaryJson string    `db:"summary_json" json:"summary_json"`
}

func (q *Queries) InsertCoverageRun(ctx context.Context, arg InsertCoverageRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCoverageRun,
		arg.Framework,
		arg.StartedAt,
		arg.FinishedAt,
		arg.RawPath,
		arg.SummaryJson,
	)
}

const listAllCoverageRuns = `-- name: ListAllCoverageRuns :many
SELECT id, framework, started_at, finished_at, raw_path, summary_json
FROM coverage_runs
ORDER BY finished_at DESC, id DESC
`

func (q *Queries) ListAllCoverageRuns(ctx context.Context) ([]CoverageRun, error) {
	rows, err := q.db.QueryContext(ctx, listAllCoverageRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoverageRun{}
	for rows.Next() {
		var i CoverageRun
		if err := rows.Scan(
			&i.ID,
			&i.Framework,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RawPath,
			&i.SummaryJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoverageResults = `-- name: ListCoverageResults :many
SELECT id, run_id, symbol_id, feature_id, status, duration_ms, message
FROM coverage_results
WHERE run_id = ?
ORDER BY id
`

func (q *Queries) ListCoverageResults(ctx context.Context, runID int64) ([]CoverageResult, error) {
	rows, err := q.db.QueryContext(ctx, listCoverageResults, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoverageResult{}
	for rows.Next() {
		var i CoverageResult
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.SymbolID,
			&i.FeatureID,
			&i.Status,
			&i.DurationMs,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoverageRunsByFramework = `-- name: ListCoverageRunsByFramework :many
SELECT id, framework, started_at, finished_at, raw_path, summary_json
FROM coverage_runs
WHERE framework = ?
ORDER BY finished_at DESC, id DESC
`

func (q *Queries) ListCoverageRunsByFramework(ctx context.Context, framework string) ([]CoverageRun, error) {
	rows, err := q.db.QueryContext(ctx, listCoverageRunsByFramework, framework)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoverageRun{}
	for rows.Next() {
		var i CoverageRun
		if err := rows.Scan(
			&i.ID,
			&i.Framework,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RawPath,
			&i.SummaryJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
