// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edges.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteEdgesByFile = `-- name: DeleteEdgesByFile :exec
DELETE FROM edges WHERE file_path = ?
`

func (q *Queries) DeleteEdgesByFile(ctx context.Context, filePath string) error {
	_, err := q.db.ExecContext(ctx, deleteEdgesByFile, filePath)
	return err
}

const getEdgeID = `-- name: GetEdgeID :one
SELECT id FROM edges
WHERE from_symbol_id = ?
  AND to_symbol_id = ?
  AND kind = ?
  AND file_path = ?
  AND line = ?
`

type GetEdgeIDParams struct {
	FromSymbolID int64  `db:"from_symbol_id" json:"from_symbol_id"`
	ToSymbolID   int64  `db:"to_symbol_id" json:"to_symbol_id"`
	Kind         string `db:"kind" json:"kind"`
	FilePath     string `db:"file_path" json:"file_path"`
	Line         int64  `db:"line" json:"line"`
}

func (q *Queries) GetEdgeID(ctx context.Context, arg GetEdgeIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEdgeID,
		arg.FromSymbolID,
		arg.ToSymbolID,
		arg.Kind,
		arg.FilePath,
		arg.Line,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertEdge = `-- name: InsertEdge :execresult
INSERT OR IGNORE INTO edges
  (from_symbol_id, to_symbol_id, kind, file_path, line, edge_meta)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertEdgeParams struct {
	FromSymbolID int64   `db:"from_symbol_id" json:"from_symbol_id"`
	ToSymbolID   int64   `db:"to_symbol_id" json:"to_symbol_id"`
	Kind         string  `db:"kind" json:"kind"`
	FilePath     string  `db:"file_path" json:"file_path"`
	Line         int64   `db:"line" json:"line"`
	EdgeMeta     *string `db:"edge_meta" json:"edge_meta"`
}

// edge_meta is a NULLable kind-specific qualifier. Python import edges populate it with a scope tag (module/function/conditional/type_checking/try_guard) via migration 0008 - issue #16. Non-import edges pass NULL.
func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertEdge,
		arg.FromSymbolID,
		arg.ToSymbolID,
		arg.Kind,
		arg.FilePath,
		arg.Line,
		arg.EdgeMeta,
	)
}

const listEdgesIn = `-- name: ListEdgesIn :many
SELECT id, from_symbol_id, to_symbol_id, kind, file_path, line, edge_meta, created_at
FROM edges
WHERE to_symbol_id = ?
ORDER BY file_path, line
`

type ListEdgesInRow struct {
	ID           int64     `db:"id" json:"id"`
	FromSymbolID int64     `db:"from_symbol_id" json:"from_symbol_id"`
	ToSymbolID   int64     `db:"to_symbol_id" json:"to_symbol_id"`
	Kind         string    `db:"kind" json:"kind"`
	FilePath     string    `db:"file_path" json:"file_path"`
	Line         int64     `db:"line" json:"line"`
	EdgeMeta     *string   `db:"edge_meta" json:"edge_meta"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) ListEdgesIn(ctx context.Context, toSymbolID int64) ([]ListEdgesInRow, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesIn, toSymbolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEdgesInRow{}
	for rows.Next() {
		var i ListEdgesInRow
		if err := rows.Scan(
			&i.ID,
			&i.FromSymbolID,
			&i.ToSymbolID,
			&i.Kind,
			&i.FilePath,
			&i.Line,
			&i.EdgeMeta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesOut = `-- name: ListEdgesOut :many
SELECT id, from_symbol_id, to_symbol_id, kind, file_path, line, edge_meta, created_at
FROM edges
WHERE from_symbol_id = ?
ORDER BY file_path, line
`

type ListEdgesOutRow struct {
	ID           int64     `db:"id" json:"id"`
	FromSymbolID int64     `db:"from_symbol_id" json:"from_symbol_id"`
	ToSymbolID   int64     `db:"to_symbol_id" json:"to_symbol_id"`
	Kind         string    `db:"kind" json:"kind"`
	FilePath     string    `db:"file_path" json:"file_path"`
	Line         int64     `db:"line" json:"line"`
	EdgeMeta     *string   `db:"edge_meta" json:"edge_meta"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) ListEdgesOut(ctx context.Context, fromSymbolID int64) ([]ListEdgesOutRow, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesOut, fromSymbolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEdgesOutRow{}
	for rows.Next() {
		var i ListEdgesOutRow
		if err := rows.Scan(
			&i.ID,
			&i.FromSymbolID,
			&i.ToSymbolID,
			&i.Kind,
			&i.FilePath,
			&i.Line,
			&i.EdgeMeta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
