// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: features.sql

package sqlc

import (
	"context"
)

const deleteFeature = `-- name: DeleteFeature :execrows
DELETE FROM features WHERE id = ?
`

func (q *Queries) DeleteFeature(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFeature, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFeature = `-- name: GetFeature :one
SELECT id, title, owner, kind, deprecated_since, introduced_in, created_at, updated_at
FROM features
WHERE id = ?
`

func (q *Queries) GetFeature(ctx context.Context, id string) (Feature, error) {
	row := q.db.QueryRowContext(ctx, getFeature, id)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Owner,
		&i.Kind,
		&i.DeprecatedSince,
		&i.IntroducedIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllFeatures = `-- name: ListAllFeatures :many
SELECT id, title, owner, kind, deprecated_since, introduced_in, created_at, updated_at
FROM features
ORDER BY id
`

func (q *Queries) ListAllFeatures(ctx context.Context) ([]Feature, error) {
	rows, err := q.db.QueryContext(ctx, listAllFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feature{}
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Owner,
			&i.Kind,
			&i.DeprecatedSince,
			&i.IntroducedIn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturesByKind = `-- name: ListFeaturesByKind :many
SELECT id, title, owner, kind, deprecated_since, introduced_in, created_at, updated_at
FROM features
WHERE kind = ?
ORDER BY id
`

func (q *Queries) ListFeaturesByKind(ctx context.Context, kind string) ([]Feature, error) {
	rows, err := q.db.QueryContext(ctx, listFeaturesByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feature{}
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Owner,
			&i.Kind,
			&i.DeprecatedSince,
			&i.IntroducedIn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeature = `-- name: UpsertFeature :exec
INSERT INTO features (id, title, owner, kind, deprecated_since, introduced_in, updated_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  title            = excluded.title,
  owner            = excluded.owner,
  kind             = excluded.kind,
  deprecated_since = excluded.deprecated_since,
  introduced_in    = excluded.introduced_in,
  updated_at       = CURRENT_TIMESTAMP
`

type UpsertFeatureParams struct {
	ID              string  `db:"id" json:"id"`
	Title           string  `db:"title" json:"title"`
	Owner           *string `db:"owner" json:"owner"`
	Kind            string  `db:"kind" json:"kind"`
	DeprecatedSince *string `db:"deprecated_since" json:"deprecated_since"`
	IntroducedIn    *string `db:"introduced_in" json:"introduced_in"`
}

func (q *Queries) UpsertFeature(ctx context.Context, arg UpsertFeatureParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeature,
		arg.ID,
		arg.Title,
		arg.Owner,
		arg.Kind,
		arg.DeprecatedSince,
		arg.IntroducedIn,
	)
	return err
}
