// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feature_symbols.sql

package sqlc

import (
	"context"
)

const linkFeatureSymbol = `-- name: LinkFeatureSymbol :exec
INSERT OR IGNORE INTO feature_symbols (feature_id, symbol_id, role, source)
VALUES (?, ?, ?, ?)
`

type LinkFeatureSymbolParams struct {
	FeatureID string `db:"feature_id" json:"feature_id"`
	SymbolID  int64  `db:"symbol_id" json:"symbol_id"`
	Role      string `db:"role" json:"role"`
	Source    string `db:"source" json:"source"`
}

func (q *Queries) LinkFeatureSymbol(ctx context.Context, arg LinkFeatureSymbolParams) error {
	_, err := q.db.ExecContext(ctx, linkFeatureSymbol,
		arg.FeatureID,
		arg.SymbolID,
		arg.Role,
		arg.Source,
	)
	return err
}

const listFeatureSymbolsByFeature = `-- name: ListFeatureSymbolsByFeature :many
SELECT feature_id, symbol_id, role, source
FROM feature_symbols
WHERE feature_id = ?
ORDER BY role, symbol_id
`

func (q *Queries) ListFeatureSymbolsByFeature(ctx context.Context, featureID string) ([]FeatureSymbol, error) {
	rows, err := q.db.QueryContext(ctx, listFeatureSymbolsByFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureSymbol{}
	for rows.Next() {
		var i FeatureSymbol
		if err := rows.Scan(
			&i.FeatureID,
			&i.SymbolID,
			&i.Role,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureSymbolsBySymbol = `-- name: ListFeatureSymbolsBySymbol :many
SELECT feature_id, symbol_id, role, source
FROM feature_symbols
WHERE symbol_id = ?
ORDER BY feature_id, role
`

func (q *Queries) ListFeatureSymbolsBySymbol(ctx context.Context, symbolID int64) ([]FeatureSymbol, error) {
	rows, err := q.db.QueryContext(ctx, listFeatureSymbolsBySymbol, symbolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureSymbol{}
	for rows.Next() {
		var i FeatureSymbol
		if err := rows.Scan(
			&i.FeatureID,
			&i.SymbolID,
			&i.Role,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkFeatureSymbol = `-- name: UnlinkFeatureSymbol :execrows
DELETE FROM feature_symbols
WHERE feature_id = ? AND symbol_id = ? AND role = ?
`

type UnlinkFeatureSymbolParams struct {
	FeatureID string `db:"feature_id" json:"feature_id"`
	SymbolID  int64  `db:"symbol_id" json:"symbol_id"`
	Role      string `db:"role" json:"role"`
}

func (q *Queries) UnlinkFeatureSymbol(ctx context.Context, arg UnlinkFeatureSymbolParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unlinkFeatureSymbol, arg.FeatureID, arg.SymbolID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
