// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_hashes.sql

package sqlc

import (
	"context"
	"time"
)

const deleteFileHash = `-- name: DeleteFileHash :exec
DELETE FROM file_hashes WHERE file_path = ?
`

func (q *Queries) DeleteFileHash(ctx context.Context, filePath string) error {
	_, err := q.db.ExecContext(ctx, deleteFileHash, filePath)
	return err
}

const getFileHash = `-- name: GetFileHash :one
SELECT file_path, content_hash, mtime, last_scanned
FROM file_hashes
WHERE file_path = ?
`

func (q *Queries) GetFileHash(ctx context.Context, filePath string) (FileHash, error) {
	row := q.db.QueryRowContext(ctx, getFileHash, filePath)
	var i FileHash
	err := row.Scan(
		&i.FilePath,
		&i.ContentHash,
		&i.Mtime,
		&i.LastScanned,
	)
	return i, err
}

const listFileHashes = `-- name: ListFileHashes :many
SELECT file_path, content_hash, mtime, last_scanned
FROM file_hashes
ORDER BY file_path
`

func (q *Queries) ListFileHashes(ctx context.Context) ([]FileHash, error) {
	rows, err := q.db.QueryContext(ctx, listFileHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileHash{}
	for rows.Next() {
		var i FileHash
		if err := rows.Scan(
			&i.FilePath,
			&i.ContentHash,
			&i.Mtime,
			&i.LastScanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFileHash = `-- name: UpsertFileHash :exec
INSERT INTO file_hashes (file_path, content_hash, mtime, last_scanned)
VALUES (?, ?, ?, ?)
ON CONFLICT(file_path) DO UPDATE SET
  content_hash = excluded.content_hash,
  mtime        = excluded.mtime,
  last_scanned = excluded.last_scanned
`

type UpsertFileHashParams struct {
	FilePath    string    `db:"file_path" json:"file_path"`
	ContentHash string    `db:"content_hash" json:"content_hash"`
	Mtime       time.Time `db:"mtime" json:"mtime"`
	LastScanned time.Time `db:"last_scanned" json:"last_scanned"`
}

func (q *Queries) UpsertFileHash(ctx context.Context, arg UpsertFileHashParams) error {
	_, err := q.db.ExecContext(ctx, upsertFileHash,
		arg.FilePath,
		arg.ContentHash,
		arg.Mtime,
		arg.LastScanned,
	)
	return err
}
