// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sqlc

import (
	"context"
	"time"
)

const deleteHistoryFeatures = `-- name: DeleteHistoryFeatures :exec
DELETE FROM coverage_history_features WHERE history_id = ?
`

func (q *Queries) DeleteHistoryFeatures(ctx context.Context, historyID int64) error {
	_, err := q.db.ExecContext(ctx, deleteHistoryFeatures, historyID)
	return err
}

const getHistoryPoint = `-- name: GetHistoryPoint :one
SELECT id, commit_sha, measured_at, score, denominator, note
FROM coverage_history
WHERE commit_sha = ?
`

// Column order matches the table declaration so sqlc reuses the generated
// model type rather than inventing a per-query row type. Same for every
// SELECT below.
func (q *Queries) GetHistoryPoint(ctx context.Context, commitSha string) (CoverageHistory, error) {
	row := q.db.QueryRowContext(ctx, getHistoryPoint, commitSha)
	var i CoverageHistory
	err := row.Scan(
		&i.ID,
		&i.CommitSha,
		&i.MeasuredAt,
		&i.Score,
		&i.Denominator,
		&i.Note,
	)
	return i, err
}

const historyPointIDByCommit = `-- name: HistoryPointIDByCommit :one
SELECT id FROM coverage_history WHERE commit_sha = ?
`

func (q *Queries) HistoryPointIDByCommit(ctx context.Context, commitSha string) (int64, error) {
	row := q.db.QueryRowContext(ctx, historyPointIDByCommit, commitSha)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertHistoryFeature = `-- name: InsertHistoryFeature :exec
INSERT INTO coverage_history_features (history_id, feature_id, score, denominator)
VALUES (?, ?, ?, ?)
`

type InsertHistoryFeatureParams struct {
	HistoryID   int64    `db:"history_id" json:"history_id"`
	FeatureID   string   `db:"feature_id" json:"feature_id"`
	Score       *float64 `db:"score" json:"score"`
	Denominator int64    `db:"denominator" json:"denominator"`
}

func (q *Queries) InsertHistoryFeature(ctx context.Context, arg InsertHistoryFeatureParams) error {
	_, err := q.db.ExecContext(ctx, insertHistoryFeature,
		arg.HistoryID,
		arg.FeatureID,
		arg.Score,
		arg.Denominator,
	)
	return err
}

const listHistoryFeatures = `-- name: ListHistoryFeatures :many
SELECT history_id, feature_id, score, denominator
FROM coverage_history_features
WHERE history_id = ?
ORDER BY feature_id
`

func (q *Queries) ListHistoryFeatures(ctx context.Context, historyID int64) ([]CoverageHistoryFeature, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryFeatures, historyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoverageHistoryFeature{}
	for rows.Next() {
		var i CoverageHistoryFeature
		if err := rows.Scan(
			&i.HistoryID,
			&i.FeatureID,
			&i.Score,
			&i.Denominator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryPoints = `-- name: ListHistoryPoints :many
SELECT id, commit_sha, measured_at, score, denominator, note
FROM coverage_history
WHERE measured_at >= ?
ORDER BY measured_at DESC, id DESC
LIMIT ?
`

type ListHistoryPointsParams struct {
	MeasuredAt time.Time `db:"measured_at" json:"measured_at"`
	Limit      int64     `db:"limit" json:"limit"`
}

// Newest first with a LIMIT so a cap keeps the most RECENT window; the port
// reverses into oldest-first, which is how a series reads.
func (q *Queries) ListHistoryPoints(ctx context.Context, arg ListHistoryPointsParams) ([]CoverageHistory, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryPoints, arg.MeasuredAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoverageHistory{}
	for rows.Next() {
		var i CoverageHistory
		if err := rows.Scan(
			&i.ID,
			&i.CommitSha,
			&i.MeasuredAt,
			&i.Score,
			&i.Denominator,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneHistoryBefore = `-- name: PruneHistoryBefore :execrows
DELETE FROM coverage_history WHERE measured_at < ?
`

// Retention. The per-feature rows go with the point via ON DELETE CASCADE,
// so there is no second statement to forget.
func (q *Queries) PruneHistoryBefore(ctx context.Context, measuredAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneHistoryBefore, measuredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertHistoryPoint = `-- name: UpsertHistoryPoint :exec
INSERT INTO coverage_history (commit_sha, measured_at, score, denominator, note)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(commit_sha) DO UPDATE SET
  measured_at = excluded.measured_at,
  score       = excluded.score,
  denominator = excluded.denominator,
  note        = excluded.note
`

type UpsertHistoryPointParams struct {
	CommitSha   string    `db:"commit_sha" json:"commit_sha"`
	MeasuredAt  time.Time `db:"measured_at" json:"measured_at"`
	Score       *float64  `db:"score" json:"score"`
	Denominator int64     `db:"denominator" json:"denominator"`
	Note        *string   `db:"note" json:"note"`
}

// coverage_history is the measurement series behind `atlas trend` (#92).
// A re-measurement of a commit CORRECTS its point, it does not append a
// second one, so the write is an upsert on the unique commit_sha index.
// last_insert_rowid() is not updated on the DO UPDATE path, which is why
// the caller reads the id back with HistoryPointIDByCommit instead of
// trusting an execresult here.
func (q *Queries) UpsertHistoryPoint(ctx context.Context, arg UpsertHistoryPointParams) error {
	_, err := q.db.ExecContext(ctx, upsertHistoryPoint,
		arg.CommitSha,
		arg.MeasuredAt,
		arg.Score,
		arg.Denominator,
		arg.Note,
	)
	return err
}
