// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Annotation struct {
	ID       int64     `db:"id" json:"id"`
	FilePath string    `db:"file_path" json:"file_path"`
	Line     int64     `db:"line" json:"line"`
	Kind     string    `db:"kind" json:"kind"`
	Value    string    `db:"value" json:"value"`
	Source   string    `db:"source" json:"source"`
	ParsedAt time.Time `db:"parsed_at" json:"parsed_at"`
}

type AuditSnapshotRun struct {
	ID         int64     `db:"id" json:"id"`
	ComputedAt time.Time `db:"computed_at" json:"computed_at"`
	ScoreJson  string    `db:"score_json" json:"score_json"`
}

type Config struct {
	Key       string    `db:"key" json:"key"`
	Value     string    `db:"value" json:"value"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type CoverageResult struct {
	ID         int64   `db:"id" json:"id"`
	RunID      int64   `db:"run_id" json:"run_id"`
	SymbolID   *int64  `db:"symbol_id" json:"symbol_id"`
	FeatureID  *string `db:"feature_id" json:"feature_id"`
	Status     string  `db:"status" json:"status"`
	DurationMs int64   `db:"duration_ms" json:"duration_ms"`
	Message    *string `db:"message" json:"message"`
}

type CoverageRun struct {
	ID          int64     `db:"id" json:"id"`
	Framework   string    `db:"framework" json:"framework"`
	StartedAt   time.Time `db:"started_at" json:"started_at"`
	FinishedAt  time.Time `db:"finished_at" json:"finished_at"`
	RawPath     *string   `db:"raw_path" json:"raw_path"`
	SummaryJson string    `db:"summary_json" json:"summary_json"`
}

type Edge struct {
	ID           int64     `db:"id" json:"id"`
	FromSymbolID int64     `db:"from_symbol_id" json:"from_symbol_id"`
	ToSymbolID   int64     `db:"to_symbol_id" json:"to_symbol_id"`
	Kind         string    `db:"kind" json:"kind"`
	FilePath     string    `db:"file_path" json:"file_path"`
	Line         int64     `db:"line" json:"line"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	EdgeMeta     *string   `db:"edge_meta" json:"edge_meta"`
}

type Feature struct {
	ID              string    `db:"id" json:"id"`
	Title           string    `db:"title" json:"title"`
	Owner           *string   `db:"owner" json:"owner"`
	Kind            string    `db:"kind" json:"kind"`
	DeprecatedSince *string   `db:"deprecated_since" json:"deprecated_since"`
	IntroducedIn    *string   `db:"introduced_in" json:"introduced_in"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}

type FeatureSymbol struct {
	FeatureID string `db:"feature_id" json:"feature_id"`
	SymbolID  int64  `db:"symbol_id" json:"symbol_id"`
	Role      string `db:"role" json:"role"`
	Source    string `db:"source" json:"source"`
}

type FileHash struct {
	FilePath    string    `db:"file_path" json:"file_path"`
	ContentHash string    `db:"content_hash" json:"content_hash"`
	Mtime       time.Time `db:"mtime" json:"mtime"`
	LastScanned time.Time `db:"last_scanned" json:"last_scanned"`
}

type Snapshot struct {
	ID         int64     `db:"id" json:"id"`
	GitRef     string    `db:"git_ref" json:"git_ref"`
	CapturedAt time.Time `db:"captured_at" json:"captured_at"`
	IndexJson  string    `db:"index_json" json:"index_json"`
	AuditJson  *string   `db:"audit_json" json:"audit_json"`
	Notes      *string   `db:"notes" json:"notes"`
}

type Symbol struct {
	ID             int64     `db:"id" json:"id"`
	QualifiedName  string    `db:"qualified_name" json:"qualified_name"`
	Kind           string    `db:"kind" json:"kind"`
	FilePath       string    `db:"file_path" json:"file_path"`
	Line           int64     `db:"line" json:"line"`
	EndLine        *int64    `db:"end_line" json:"end_line"`
	Package        *string   `db:"package" json:"package"`
	BcPath         *string   `db:"bc_path" json:"bc_path"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	PatternMatches *string   `db:"pattern_matches" json:"pattern_matches"`
}
