// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteAnnotationsByFile(ctx context.Context, filePath string) error
	DeleteConfig(ctx context.Context, key string) error
	DeleteEdgesByFile(ctx context.Context, filePath string) error
	DeleteFeature(ctx context.Context, id string) (int64, error)
	DeleteFileHash(ctx context.Context, filePath string) error
	DeleteSnapshot(ctx context.Context, id int64) (int64, error)
	DeleteSymbolsByFile(ctx context.Context, filePath string) error
	// Inserts a feature row from the ingest path. Pure INSERT OR IGNORE -- if
	// the row already exists with richer metadata (title/owner/kind/etc set
	// by a prior atlas migrate or test harness), the ingest pass MUST NOT
	// clobber it back to the id-as-title default.
	//
	// Re-ingest of the same annotation produces zero row changes. Use the
	// explicit UpsertFeature path when callers genuinely want to overwrite.
	EnsureFeature(ctx context.Context, arg EnsureFeatureParams) error
	GetAuditSnapshotRun(ctx context.Context, id int64) (AuditSnapshotRun, error)
	GetConfig(ctx context.Context, key string) (string, error)
	GetCoverageRun(ctx context.Context, id int64) (CoverageRun, error)
	GetEdgeID(ctx context.Context, arg GetEdgeIDParams) (int64, error)
	GetFeature(ctx context.Context, id string) (Feature, error)
	GetFileHash(ctx context.Context, filePath string) (FileHash, error)
	GetSnapshot(ctx context.Context, id int64) (Snapshot, error)
	GetSymbolByQualifiedName(ctx context.Context, qualifiedName string) (Symbol, error)
	GetSymbolIDByQualifiedName(ctx context.Context, qualifiedName string) (int64, error)
	InsertAuditSnapshotRun(ctx context.Context, scoreJson string) (sql.Result, error)
	InsertAuditSnapshotRunWithTime(ctx context.Context, arg InsertAuditSnapshotRunWithTimeParams) (sql.Result, error)
	InsertCoverageResult(ctx context.Context, arg InsertCoverageResultParams) error
	InsertCoverageRun(ctx context.Context, arg InsertCoverageRunParams) (sql.Result, error)
	// edge_meta is a NULLable kind-specific qualifier. Python import edges populate it with a scope tag (module/function/conditional/type_checking/try_guard) via migration 0008 - issue #16. Non-import edges pass NULL.
	InsertEdge(ctx context.Context, arg InsertEdgeParams) (sql.Result, error)
	InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (sql.Result, error)
	InsertSymbol(ctx context.Context, arg InsertSymbolParams) (sql.Result, error)
	LatestAuditSnapshotRun(ctx context.Context) (AuditSnapshotRun, error)
	LinkFeatureSymbol(ctx context.Context, arg LinkFeatureSymbolParams) error
	ListAllCoverageRuns(ctx context.Context) ([]CoverageRun, error)
	ListAllFeatures(ctx context.Context) ([]Feature, error)
	ListAllSnapshots(ctx context.Context) ([]Snapshot, error)
	ListAnnotationsByFile(ctx context.Context, filePath string) ([]Annotation, error)
	ListAuditSnapshotRuns(ctx context.Context, limit int64) ([]AuditSnapshotRun, error)
	ListConfig(ctx context.Context) ([]Config, error)
	ListCoverageResults(ctx context.Context, runID int64) ([]CoverageResult, error)
	ListCoverageRunsByFramework(ctx context.Context, framework string) ([]CoverageRun, error)
	ListEdgesIn(ctx context.Context, toSymbolID int64) ([]ListEdgesInRow, error)
	ListEdgesOut(ctx context.Context, fromSymbolID int64) ([]ListEdgesOutRow, error)
	ListFeatureSymbolsByFeature(ctx context.Context, featureID string) ([]FeatureSymbol, error)
	ListFeatureSymbolsBySymbol(ctx context.Context, symbolID int64) ([]FeatureSymbol, error)
	ListFeaturesByKind(ctx context.Context, kind string) ([]Feature, error)
	ListFileHashes(ctx context.Context) ([]FileHash, error)
	ListSnapshotsByGitRef(ctx context.Context, gitRef string) ([]Snapshot, error)
	// Returns rows that match every non-empty filter, ordered deterministically.
	// Each filter is opt-in via the sentinel-empty-string idiom: pass the empty
	// string for a column to disable that predicate; pass a value to match it
	// exactly. We use sentinels instead of sqlc.narg because as of sqlc v1.31.1
	// the sqlite engine ANTLR grammar rejects the post-substituted placeholders
	// the narg lowering emits (see sqlc-dev/sqlc#1881, #3508).
	//
	// None of these columns store the empty value as a legitimate row: the
	// parser layer always populates file_path + kind, and package / bc_path
	// are either non-empty or NULL.
	//
	// Callers must normalize Kind to the closed schema-v1 set BEFORE binding
	// (see normalizeKind) so the equality match never silently misses an
	// audit-layer value that would have collapsed at insert time.
	ListSymbols(ctx context.Context, arg ListSymbolsParams) ([]Symbol, error)
	// Resolves an annotation at file:line to the symbol it attaches to. Atlas
	// annotations sit in the comment block immediately above their target
	// (Go: doc comment above the func decl). The "nearest symbol at or after
	// the annotation line, in the same file, within `max_lookahead` rows"
	// rule is the simplest invariant that captures both `@atlas:feature`
	// (one line above the func) and multi-line doc-block annotations
	// (several lines above).
	//
	// Bounds are deliberate: drifting more than ~30 lines past the annotation
	// almost always indicates the annotation is orphan (comment-only file or
	// markdown), not a legitimate attach to a faraway function.
	LookupSymbolAtOrAfterLine(ctx context.Context, arg LookupSymbolAtOrAfterLineParams) (Symbol, error)
	SetConfig(ctx context.Context, arg SetConfigParams) error
	SetSymbolPatternMatches(ctx context.Context, arg SetSymbolPatternMatchesParams) error
	SetSymbolPatternMatchesByQualifiedName(ctx context.Context, arg SetSymbolPatternMatchesByQualifiedNameParams) error
	UnlinkFeatureSymbol(ctx context.Context, arg UnlinkFeatureSymbolParams) (int64, error)
	UpsertAnnotation(ctx context.Context, arg UpsertAnnotationParams) error
	UpsertFeature(ctx context.Context, arg UpsertFeatureParams) error
	UpsertFileHash(ctx context.Context, arg UpsertFileHashParams) error
}

var _ Querier = (*Queries)(nil)
