// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skipped.sql

package sqlc

import (
	"context"
	"time"
)

const deleteAllSkippedFiles = `-- name: DeleteAllSkippedFiles :exec
DELETE FROM skipped_files
`

func (q *Queries) DeleteAllSkippedFiles(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSkippedFiles)
	return err
}

const getSkippedFile = `-- name: GetSkippedFile :one
SELECT file_path, rule, detail, scanned_at
FROM skipped_files
WHERE file_path = ?
`

func (q *Queries) GetSkippedFile(ctx context.Context, filePath string) (SkippedFile, error) {
	row := q.db.QueryRowContext(ctx, getSkippedFile, filePath)
	var i SkippedFile
	err := row.Scan(
		&i.FilePath,
		&i.Rule,
		&i.Detail,
		&i.ScannedAt,
	)
	return i, err
}

const insertSkippedFile = `-- name: InsertSkippedFile :exec
INSERT INTO skipped_files (file_path, rule, detail, scanned_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(file_path) DO NOTHING
`

type InsertSkippedFileParams struct {
	FilePath  string    `db:"file_path" json:"file_path"`
	Rule      string    `db:"rule" json:"rule"`
	Detail    *string   `db:"detail" json:"detail"`
	ScannedAt time.Time `db:"scanned_at" json:"scanned_at"`
}

// DO NOTHING rather than DO UPDATE: within one scan a file is claimed by
// exactly one rule, so a second row for the same path can only come from a
// caller merging two scans. Keeping the first entry keeps the scanner's own
// decision instead of letting the merge order rewrite it.
func (q *Queries) InsertSkippedFile(ctx context.Context, arg InsertSkippedFileParams) error {
	_, err := q.db.ExecContext(ctx, insertSkippedFile,
		arg.FilePath,
		arg.Rule,
		arg.Detail,
		arg.ScannedAt,
	)
	return err
}

const listSkippedFiles = `-- name: ListSkippedFiles :many
SELECT file_path, rule, detail, scanned_at
FROM skipped_files
ORDER BY file_path
`

func (q *Queries) ListSkippedFiles(ctx context.Context) ([]SkippedFile, error) {
	rows, err := q.db.QueryContext(ctx, listSkippedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkippedFile{}
	for rows.Next() {
		var i SkippedFile
		if err := rows.Scan(
			&i.FilePath,
			&i.Rule,
			&i.Detail,
			&i.ScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
