// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteSnapshot = `-- name: DeleteSnapshot :execrows
DELETE FROM snapshots WHERE id = ?
`

func (q *Queries) DeleteSnapshot(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSnapshot, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT id, git_ref, captured_at, index_json, audit_json, notes
FROM snapshots
WHERE id = ?
`

func (q *Queries) GetSnapshot(ctx context.Context, id int64) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshot, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.GitRef,
		&i.CapturedAt,
		&i.IndexJson,
		&i.AuditJson,
		&i.Notes,
	)
	return i, err
}

const insertSnapshot = `-- name: InsertSnapshot :execresult
INSERT INTO snapshots (git_ref, captured_at, index_json, audit_json, notes)
VALUES (?, ?, ?, ?, ?)
`

type InsertSnapshotParams struct {
	GitRef     string    `db:"git_ref" json:"git_ref"`
	CapturedAt time.Time `db:"captured_at" json:"captured_at"`
	IndexJson  string    `db:"index_json" json:"index_json"`
	AuditJson  *string   `db:"audit_json" json:"audit_json"`
	Notes      *string   `db:"notes" json:"notes"`
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSnapshot,
		arg.GitRef,
		arg.CapturedAt,
		arg.IndexJson,
		arg.AuditJson,
		arg.Notes,
	)
}

const listAllSnapshots = `-- name: ListAllSnapshots :many
SELECT id, git_ref, captured_at, index_json, audit_json, notes
FROM snapshots
ORDER BY captured_at DESC, id DESC
`

func (q *Queries) ListAllSnapshots(ctx context.Context) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listAllSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.GitRef,
			&i.CapturedAt,
			&i.IndexJson,
			&i.AuditJson,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByGitRef = `-- name: ListSnapshotsByGitRef :many
SELECT id, git_ref, captured_at, index_json, audit_json, notes
FROM snapshots
WHERE git_ref = ?
ORDER BY captured_at DESC, id DESC
`

func (q *Queries) ListSnapshotsByGitRef(ctx context.Context, gitRef string) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByGitRef, gitRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.GitRef,
			&i.CapturedAt,
			&i.IndexJson,
			&i.AuditJson,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
