// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sqlops.sql

package sqlc

import (
	"context"
)

const countSQLOperationsByResolution = `-- name: CountSQLOperationsByResolution :many
SELECT resolved, COUNT(*) AS total
FROM sql_operations
GROUP BY resolved
`

type CountSQLOperationsByResolutionRow struct {
	Resolved int64 `db:"resolved" json:"resolved"`
	Total    int64 `db:"total" json:"total"`
}

// The honesty counter, straight out of the store: how much of the data layer
// atlas could actually read.
func (q *Queries) CountSQLOperationsByResolution(ctx context.Context) ([]CountSQLOperationsByResolutionRow, error) {
	rows, err := q.db.QueryContext(ctx, countSQLOperationsByResolution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSQLOperationsByResolutionRow{}
	for rows.Next() {
		var i CountSQLOperationsByResolutionRow
		if err := rows.Scan(&i.Resolved, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllSQLIndexes = `-- name: DeleteAllSQLIndexes :exec
DELETE FROM sql_indexes
`

func (q *Queries) DeleteAllSQLIndexes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSQLIndexes)
	return err
}

const deleteAllSQLOperations = `-- name: DeleteAllSQLOperations :exec
DELETE FROM sql_operations
`

// The operation inventory is replaced wholesale on every scan. An incremental
// upsert would leave rows behind for queries that were deleted, and a stale
// advisory pointing at a line that no longer exists is worse than no advisory.
func (q *Queries) DeleteAllSQLOperations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSQLOperations)
	return err
}

const deleteAllSQLTables = `-- name: DeleteAllSQLTables :exec
DELETE FROM sql_tables
`

func (q *Queries) DeleteAllSQLTables(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSQLTables)
	return err
}

const insertSQLIndex = `-- name: InsertSQLIndex :exec
INSERT OR REPLACE INTO sql_indexes
  (table_name, name, columns, is_unique, predicate, origin, file_path, line)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSQLIndexParams struct {
	TableName string `db:"table_name" json:"table_name"`
	Name      string `db:"name" json:"name"`
	Columns   string `db:"columns" json:"columns"`
	IsUnique  int64  `db:"is_unique" json:"is_unique"`
	Predicate string `db:"predicate" json:"predicate"`
	Origin    string `db:"origin" json:"origin"`
	FilePath  string `db:"file_path" json:"file_path"`
	Line      int64  `db:"line" json:"line"`
}

func (q *Queries) InsertSQLIndex(ctx context.Context, arg InsertSQLIndexParams) error {
	_, err := q.db.ExecContext(ctx, insertSQLIndex,
		arg.TableName,
		arg.Name,
		arg.Columns,
		arg.IsUnique,
		arg.Predicate,
		arg.Origin,
		arg.FilePath,
		arg.Line,
	)
	return err
}

const insertSQLOperation = `-- name: InsertSQLOperation :one
INSERT INTO sql_operations (
  ref, source, name, file_path, line, symbol_id, symbol_name, kind,
  resolved, unresolved_reason, sql_text, row_scan, param_count,
  interpolation, caller_data, has_limit, has_offset, has_order_by,
  keyset, select_star, offset_bound, suppressions
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type InsertSQLOperationParams struct {
	Ref              string `db:"ref" json:"ref"`
	Source           string `db:"source" json:"source"`
	Name             string `db:"name" json:"name"`
	FilePath         string `db:"file_path" json:"file_path"`
	Line             int64  `db:"line" json:"line"`
	SymbolID         *int64 `db:"symbol_id" json:"symbol_id"`
	SymbolName       string `db:"symbol_name" json:"symbol_name"`
	Kind             string `db:"kind" json:"kind"`
	Resolved         int64  `db:"resolved" json:"resolved"`
	UnresolvedReason string `db:"unresolved_reason" json:"unresolved_reason"`
	SqlText          string `db:"sql_text" json:"sql_text"`
	RowScan          string `db:"row_scan" json:"row_scan"`
	ParamCount       int64  `db:"param_count" json:"param_count"`
	Interpolation    string `db:"interpolation" json:"interpolation"`
	CallerData       int64  `db:"caller_data" json:"caller_data"`
	HasLimit         int64  `db:"has_limit" json:"has_limit"`
	HasOffset        int64  `db:"has_offset" json:"has_offset"`
	HasOrderBy       int64  `db:"has_order_by" json:"has_order_by"`
	Keyset           int64  `db:"keyset" json:"keyset"`
	SelectStar       int64  `db:"select_star" json:"select_star"`
	OffsetBound      string `db:"offset_bound" json:"offset_bound"`
	Suppressions     string `db:"suppressions" json:"suppressions"`
}

// Column order matches the table declaration so sqlc reuses the model type
// instead of inventing a per-query row struct.
func (q *Queries) InsertSQLOperation(ctx context.Context, arg InsertSQLOperationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSQLOperation,
		arg.Ref,
		arg.Source,
		arg.Name,
		arg.FilePath,
		arg.Line,
		arg.SymbolID,
		arg.SymbolName,
		arg.Kind,
		arg.Resolved,
		arg.UnresolvedReason,
		arg.SqlText,
		arg.RowScan,
		arg.ParamCount,
		arg.Interpolation,
		arg.CallerData,
		arg.HasLimit,
		arg.HasOffset,
		arg.HasOrderBy,
		arg.Keyset,
		arg.SelectStar,
		arg.OffsetBound,
		arg.Suppressions,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSQLOperationPredicate = `-- name: InsertSQLOperationPredicate :exec
INSERT OR REPLACE INTO sql_operation_predicates
  (operation_id, clause, table_name, column_name, operator, bound)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSQLOperationPredicateParams struct {
	OperationID int64  `db:"operation_id" json:"operation_id"`
	Clause      string `db:"clause" json:"clause"`
	TableName   string `db:"table_name" json:"table_name"`
	ColumnName  string `db:"column_name" json:"column_name"`
	Operator    string `db:"operator" json:"operator"`
	Bound       int64  `db:"bound" json:"bound"`
}

func (q *Queries) InsertSQLOperationPredicate(ctx context.Context, arg InsertSQLOperationPredicateParams) error {
	_, err := q.db.ExecContext(ctx, insertSQLOperationPredicate,
		arg.OperationID,
		arg.Clause,
		arg.TableName,
		arg.ColumnName,
		arg.Operator,
		arg.Bound,
	)
	return err
}

const insertSQLOperationTable = `-- name: InsertSQLOperationTable :exec
INSERT OR REPLACE INTO sql_operation_tables (operation_id, table_name, access)
VALUES (?, ?, ?)
`

type InsertSQLOperationTableParams struct {
	OperationID int64  `db:"operation_id" json:"operation_id"`
	TableName   string `db:"table_name" json:"table_name"`
	Access      string `db:"access" json:"access"`
}

func (q *Queries) InsertSQLOperationTable(ctx context.Context, arg InsertSQLOperationTableParams) error {
	_, err := q.db.ExecContext(ctx, insertSQLOperationTable, arg.OperationID, arg.TableName, arg.Access)
	return err
}

const insertSQLTable = `-- name: InsertSQLTable :exec
INSERT OR REPLACE INTO sql_tables (name, file_path, line) VALUES (?, ?, ?)
`

type InsertSQLTableParams struct {
	Name     string `db:"name" json:"name"`
	FilePath string `db:"file_path" json:"file_path"`
	Line     int64  `db:"line" json:"line"`
}

func (q *Queries) InsertSQLTable(ctx context.Context, arg InsertSQLTableParams) error {
	_, err := q.db.ExecContext(ctx, insertSQLTable, arg.Name, arg.FilePath, arg.Line)
	return err
}

const listSQLIndexes = `-- name: ListSQLIndexes :many
SELECT table_name, name, columns, is_unique, predicate, origin, file_path, line
FROM sql_indexes
ORDER BY table_name, name
`

func (q *Queries) ListSQLIndexes(ctx context.Context) ([]SqlIndex, error) {
	rows, err := q.db.QueryContext(ctx, listSQLIndexes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SqlIndex{}
	for rows.Next() {
		var i SqlIndex
		if err := rows.Scan(
			&i.TableName,
			&i.Name,
			&i.Columns,
			&i.IsUnique,
			&i.Predicate,
			&i.Origin,
			&i.FilePath,
			&i.Line,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSQLOperationPredicates = `-- name: ListSQLOperationPredicates :many
SELECT operation_id, clause, table_name, column_name, operator, bound
FROM sql_operation_predicates
ORDER BY operation_id, clause, table_name, column_name, operator
`

func (q *Queries) ListSQLOperationPredicates(ctx context.Context) ([]SqlOperationPredicate, error) {
	rows, err := q.db.QueryContext(ctx, listSQLOperationPredicates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SqlOperationPredicate{}
	for rows.Next() {
		var i SqlOperationPredicate
		if err := rows.Scan(
			&i.OperationID,
			&i.Clause,
			&i.TableName,
			&i.ColumnName,
			&i.Operator,
			&i.Bound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSQLOperationTables = `-- name: ListSQLOperationTables :many
SELECT operation_id, table_name, access
FROM sql_operation_tables
ORDER BY operation_id, table_name, access
`

// Every child row for every operation in one pass; the caller groups by
// operation_id. Fetching per operation would be an N+1 against the very
// pattern this feature exists to find.
func (q *Queries) ListSQLOperationTables(ctx context.Context) ([]SqlOperationTable, error) {
	rows, err := q.db.QueryContext(ctx, listSQLOperationTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SqlOperationTable{}
	for rows.Next() {
		var i SqlOperationTable
		if err := rows.Scan(&i.OperationID, &i.TableName, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSQLOperations = `-- name: ListSQLOperations :many
SELECT id, ref, source, name, file_path, line, symbol_id, symbol_name, kind,
       resolved, unresolved_reason, sql_text, row_scan, param_count,
       interpolation, caller_data, has_limit, has_offset, has_order_by,
       keyset, select_star, offset_bound, suppressions, created_at
FROM sql_operations
ORDER BY file_path, line, name
`

// Ordered by position so successive runs diff cleanly.
func (q *Queries) ListSQLOperations(ctx context.Context) ([]SqlOperation, error) {
	rows, err := q.db.QueryContext(ctx, listSQLOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SqlOperation{}
	for rows.Next() {
		var i SqlOperation
		if err := rows.Scan(
			&i.ID,
			&i.Ref,
			&i.Source,
			&i.Name,
			&i.FilePath,
			&i.Line,
			&i.SymbolID,
			&i.SymbolName,
			&i.Kind,
			&i.Resolved,
			&i.UnresolvedReason,
			&i.SqlText,
			&i.RowScan,
			&i.ParamCount,
			&i.Interpolation,
			&i.CallerData,
			&i.HasLimit,
			&i.HasOffset,
			&i.HasOrderBy,
			&i.Keyset,
			&i.SelectStar,
			&i.OffsetBound,
			&i.Suppressions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSQLTables = `-- name: ListSQLTables :many
SELECT name, file_path, line FROM sql_tables ORDER BY name
`

func (q *Queries) ListSQLTables(ctx context.Context) ([]SqlTable, error) {
	rows, err := q.db.QueryContext(ctx, listSQLTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SqlTable{}
	for rows.Next() {
		var i SqlTable
		if err := rows.Scan(&i.Name, &i.FilePath, &i.Line); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableAccessBySymbol = `-- name: ListTableAccessBySymbol :many
SELECT t.table_name, t.access
FROM sql_operation_tables t
JOIN sql_operations o ON o.id = t.operation_id
WHERE o.symbol_id = ?
ORDER BY t.table_name, t.access
`

type ListTableAccessBySymbolRow struct {
	TableName string `db:"table_name" json:"table_name"`
	Access    string `db:"access" json:"access"`
}

// The data footprint of one symbol: the tables its queries read and write.
func (q *Queries) ListTableAccessBySymbol(ctx context.Context, symbolID *int64) ([]ListTableAccessBySymbolRow, error) {
	rows, err := q.db.QueryContext(ctx, listTableAccessBySymbol, symbolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTableAccessBySymbolRow{}
	for rows.Next() {
		var i ListTableAccessBySymbolRow
		if err := rows.Scan(&i.TableName, &i.Access); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
