// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: symbols.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteSymbolsByFile = `-- name: DeleteSymbolsByFile :exec
DELETE FROM symbols WHERE file_path = ?
`

func (q *Queries) DeleteSymbolsByFile(ctx context.Context, filePath string) error {
	_, err := q.db.ExecContext(ctx, deleteSymbolsByFile, filePath)
	return err
}

const getSymbolByQualifiedName = `-- name: GetSymbolByQualifiedName :one
SELECT id, qualified_name, kind, file_path, line, end_line, package, bc_path, created_at, pattern_matches
FROM symbols
WHERE qualified_name = ?
`

func (q *Queries) GetSymbolByQualifiedName(ctx context.Context, qualifiedName string) (Symbol, error) {
	row := q.db.QueryRowContext(ctx, getSymbolByQualifiedName, qualifiedName)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.QualifiedName,
		&i.Kind,
		&i.FilePath,
		&i.Line,
		&i.EndLine,
		&i.Package,
		&i.BcPath,
		&i.CreatedAt,
		&i.PatternMatches,
	)
	return i, err
}

const getSymbolIDByQualifiedName = `-- name: GetSymbolIDByQualifiedName :one
SELECT id FROM symbols WHERE qualified_name = ?
`

func (q *Queries) GetSymbolIDByQualifiedName(ctx context.Context, qualifiedName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSymbolIDByQualifiedName, qualifiedName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSymbol = `-- name: InsertSymbol :execresult
INSERT OR IGNORE INTO symbols
  (qualified_name, kind, file_path, line, end_line, package, bc_path)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertSymbolParams struct {
	QualifiedName string  `db:"qualified_name" json:"qualified_name"`
	Kind          string  `db:"kind" json:"kind"`
	FilePath      string  `db:"file_path" json:"file_path"`
	Line          int64   `db:"line" json:"line"`
	EndLine       *int64  `db:"end_line" json:"end_line"`
	Package       *string `db:"package" json:"package"`
	BcPath        *string `db:"bc_path" json:"bc_path"`
}

func (q *Queries) InsertSymbol(ctx context.Context, arg InsertSymbolParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSymbol,
		arg.QualifiedName,
		arg.Kind,
		arg.FilePath,
		arg.Line,
		arg.EndLine,
		arg.Package,
		arg.BcPath,
	)
}

const listSymbols = `-- name: ListSymbols :many
SELECT id, qualified_name, kind, file_path, line, end_line, package, bc_path, created_at, pattern_matches
FROM symbols
WHERE (?1 = '' OR file_path = ?1)
  AND (?2   = '' OR package   = ?2)
  AND (?3   = '' OR bc_path   = ?3)
  AND (?4      = '' OR kind      = ?4)
ORDER BY file_path, line, qualified_name
`

type ListSymbolsParams struct {
	FilePath interface{} `db:"file_path" json:"file_path"`
	Package  interface{} `db:"package" json:"package"`
	BcPath   interface{} `db:"bc_path" json:"bc_path"`
	Kind     interface{} `db:"kind" json:"kind"`
}

// Returns rows that match every non-empty filter, ordered deterministically.
// Each filter is opt-in via the sentinel-empty-string idiom: pass the empty
// string for a column to disable that predicate; pass a value to match it
// exactly. We use sentinels instead of sqlc.narg because as of sqlc v1.31.1
// the sqlite engine ANTLR grammar rejects the post-substituted placeholders
// the narg lowering emits (see sqlc-dev/sqlc#1881, #3508).
//
// None of these columns store the empty value as a legitimate row: the
// parser layer always populates file_path + kind, and package / bc_path
// are either non-empty or NULL.
//
// Callers must normalize Kind to the closed schema-v1 set BEFORE binding
// (see normalizeKind) so the equality match never silently misses an
// audit-layer value that would have collapsed at insert time.
func (q *Queries) ListSymbols(ctx context.Context, arg ListSymbolsParams) ([]Symbol, error) {
	rows, err := q.db.QueryContext(ctx, listSymbols,
		arg.FilePath,
		arg.Package,
		arg.BcPath,
		arg.Kind,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Symbol{}
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.QualifiedName,
			&i.Kind,
			&i.FilePath,
			&i.Line,
			&i.EndLine,
			&i.Package,
			&i.BcPath,
			&i.CreatedAt,
			&i.PatternMatches,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupSymbolAtOrAfterLine = `-- name: LookupSymbolAtOrAfterLine :one
SELECT id, qualified_name, kind, file_path, line, end_line, package, bc_path, created_at, pattern_matches
FROM symbols
WHERE file_path = ?1
  AND line >= ?2
  AND line <= ?2 + ?3
ORDER BY line ASC
LIMIT 1
`

type LookupSymbolAtOrAfterLineParams struct {
	FilePath     string      `db:"file_path" json:"file_path"`
	Line         int64       `db:"line" json:"line"`
	MaxLookahead interface{} `db:"max_lookahead" json:"max_lookahead"`
}

// Resolves an annotation at file:line to the symbol it attaches to. Atlas
// annotations sit in the comment block immediately above their target
// (Go: doc comment above the func decl). The "nearest symbol at or after
// the annotation line, in the same file, within `max_lookahead` rows"
// rule is the simplest invariant that captures both `@atlas:feature`
// (one line above the func) and multi-line doc-block annotations
// (several lines above).
//
// Bounds are deliberate: drifting more than ~30 lines past the annotation
// almost always indicates the annotation is orphan (comment-only file or
// markdown), not a legitimate attach to a faraway function.
func (q *Queries) LookupSymbolAtOrAfterLine(ctx context.Context, arg LookupSymbolAtOrAfterLineParams) (Symbol, error) {
	row := q.db.QueryRowContext(ctx, lookupSymbolAtOrAfterLine, arg.FilePath, arg.Line, arg.MaxLookahead)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.QualifiedName,
		&i.Kind,
		&i.FilePath,
		&i.Line,
		&i.EndLine,
		&i.Package,
		&i.BcPath,
		&i.CreatedAt,
		&i.PatternMatches,
	)
	return i, err
}

const setSymbolPatternMatches = `-- name: SetSymbolPatternMatches :exec
UPDATE symbols SET pattern_matches = ? WHERE id = ?
`

type SetSymbolPatternMatchesParams struct {
	PatternMatches *string `db:"pattern_matches" json:"pattern_matches"`
	ID             int64   `db:"id" json:"id"`
}

func (q *Queries) SetSymbolPatternMatches(ctx context.Context, arg SetSymbolPatternMatchesParams) error {
	_, err := q.db.ExecContext(ctx, setSymbolPatternMatches, arg.PatternMatches, arg.ID)
	return err
}

const setSymbolPatternMatchesByQualifiedName = `-- name: SetSymbolPatternMatchesByQualifiedName :exec
UPDATE symbols SET pattern_matches = ? WHERE qualified_name = ?
`

type SetSymbolPatternMatchesByQualifiedNameParams struct {
	PatternMatches *string `db:"pattern_matches" json:"pattern_matches"`
	QualifiedName  string  `db:"qualified_name" json:"qualified_name"`
}

func (q *Queries) SetSymbolPatternMatchesByQualifiedName(ctx context.Context, arg SetSymbolPatternMatchesByQualifiedNameParams) error {
	_, err := q.db.ExecContext(ctx, setSymbolPatternMatchesByQualifiedName, arg.PatternMatches, arg.QualifiedName)
	return err
}
