// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: symbols.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteSymbolsByFile = `-- name: DeleteSymbolsByFile :exec
DELETE FROM symbols WHERE file_path = ?
`

func (q *Queries) DeleteSymbolsByFile(ctx context.Context, filePath string) error {
	_, err := q.db.ExecContext(ctx, deleteSymbolsByFile, filePath)
	return err
}

const getSymbolByQualifiedName = `-- name: GetSymbolByQualifiedName :one
SELECT id, qualified_name, kind, file_path, line, end_line, package, bc_path, created_at
FROM symbols
WHERE qualified_name = ?
`

func (q *Queries) GetSymbolByQualifiedName(ctx context.Context, qualifiedName string) (Symbol, error) {
	row := q.db.QueryRowContext(ctx, getSymbolByQualifiedName, qualifiedName)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.QualifiedName,
		&i.Kind,
		&i.FilePath,
		&i.Line,
		&i.EndLine,
		&i.Package,
		&i.BcPath,
		&i.CreatedAt,
	)
	return i, err
}

const getSymbolIDByQualifiedName = `-- name: GetSymbolIDByQualifiedName :one
SELECT id FROM symbols WHERE qualified_name = ?
`

func (q *Queries) GetSymbolIDByQualifiedName(ctx context.Context, qualifiedName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSymbolIDByQualifiedName, qualifiedName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSymbol = `-- name: InsertSymbol :execresult
INSERT OR IGNORE INTO symbols
  (qualified_name, kind, file_path, line, end_line, package, bc_path)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertSymbolParams struct {
	QualifiedName string  `db:"qualified_name" json:"qualified_name"`
	Kind          string  `db:"kind" json:"kind"`
	FilePath      string  `db:"file_path" json:"file_path"`
	Line          int64   `db:"line" json:"line"`
	EndLine       *int64  `db:"end_line" json:"end_line"`
	Package       *string `db:"package" json:"package"`
	BcPath        *string `db:"bc_path" json:"bc_path"`
}

func (q *Queries) InsertSymbol(ctx context.Context, arg InsertSymbolParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSymbol,
		arg.QualifiedName,
		arg.Kind,
		arg.FilePath,
		arg.Line,
		arg.EndLine,
		arg.Package,
		arg.BcPath,
	)
}
