// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_coverage.sql

package sqlc

import (
	"context"
)

const countTestsInRun = `-- name: CountTestsInRun :one
SELECT COUNT(DISTINCT test_symbol_id) FROM test_coverage WHERE run_id = ?
`

func (q *Queries) CountTestsInRun(ctx context.Context, runID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTestsInRun, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTestCoverage = `-- name: InsertTestCoverage :exec
INSERT OR REPLACE INTO test_coverage (run_id, test_symbol_id, symbol_id, covered_stmts, total_stmts)
VALUES (?, ?, ?, ?, ?)
`

type InsertTestCoverageParams struct {
	RunID        int64 `db:"run_id" json:"run_id"`
	TestSymbolID int64 `db:"test_symbol_id" json:"test_symbol_id"`
	SymbolID     int64 `db:"symbol_id" json:"symbol_id"`
	CoveredStmts int64 `db:"covered_stmts" json:"covered_stmts"`
	TotalStmts   int64 `db:"total_stmts" json:"total_stmts"`
}

// One row per (run, test, executed symbol). REPLACE so a re-ingest of the
// same run is idempotent rather than a constraint violation.
func (q *Queries) InsertTestCoverage(ctx context.Context, arg InsertTestCoverageParams) error {
	_, err := q.db.ExecContext(ctx, insertTestCoverage,
		arg.RunID,
		arg.TestSymbolID,
		arg.SymbolID,
		arg.CoveredStmts,
		arg.TotalStmts,
	)
	return err
}

const listSymbolsExecutedByTest = `-- name: ListSymbolsExecutedByTest :many
SELECT symbol_id, covered_stmts, total_stmts
FROM test_coverage
WHERE run_id = ? AND test_symbol_id = ?
`

type ListSymbolsExecutedByTestParams struct {
	RunID        int64 `db:"run_id" json:"run_id"`
	TestSymbolID int64 `db:"test_symbol_id" json:"test_symbol_id"`
}

type ListSymbolsExecutedByTestRow struct {
	SymbolID     int64 `db:"symbol_id" json:"symbol_id"`
	CoveredStmts int64 `db:"covered_stmts" json:"covered_stmts"`
	TotalStmts   int64 `db:"total_stmts" json:"total_stmts"`
}

// The production symbols one test ran. Union these over a feature's annotated
// tests to get its implementation surface without walking the call graph.
func (q *Queries) ListSymbolsExecutedByTest(ctx context.Context, arg ListSymbolsExecutedByTestParams) ([]ListSymbolsExecutedByTestRow, error) {
	rows, err := q.db.QueryContext(ctx, listSymbolsExecutedByTest, arg.RunID, arg.TestSymbolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSymbolsExecutedByTestRow{}
	for rows.Next() {
		var i ListSymbolsExecutedByTestRow
		if err := rows.Scan(&i.SymbolID, &i.CoveredStmts, &i.TotalStmts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestsExecutingSymbol = `-- name: ListTestsExecutingSymbol :many
SELECT test_symbol_id, covered_stmts, total_stmts
FROM test_coverage
WHERE run_id = ? AND symbol_id = ?
`

type ListTestsExecutingSymbolParams struct {
	RunID    int64 `db:"run_id" json:"run_id"`
	SymbolID int64 `db:"symbol_id" json:"symbol_id"`
}

type ListTestsExecutingSymbolRow struct {
	TestSymbolID int64 `db:"test_symbol_id" json:"test_symbol_id"`
	CoveredStmts int64 `db:"covered_stmts" json:"covered_stmts"`
	TotalStmts   int64 `db:"total_stmts" json:"total_stmts"`
}

// The inverse: which tests ran a symbol. This is affected-test selection.
func (q *Queries) ListTestsExecutingSymbol(ctx context.Context, arg ListTestsExecutingSymbolParams) ([]ListTestsExecutingSymbolRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestsExecutingSymbol, arg.RunID, arg.SymbolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestsExecutingSymbolRow{}
	for rows.Next() {
		var i ListTestsExecutingSymbolRow
		if err := rows.Scan(&i.TestSymbolID, &i.CoveredStmts, &i.TotalStmts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const symbolTestFanIn = `-- name: SymbolTestFanIn :many
SELECT symbol_id, COUNT(DISTINCT test_symbol_id) AS test_count
FROM test_coverage
WHERE run_id = ?
GROUP BY symbol_id
`

type SymbolTestFanInRow struct {
	SymbolID  int64 `db:"symbol_id" json:"symbol_id"`
	TestCount int64 `db:"test_count" json:"test_count"`
}

// symbol_id -> how many distinct tests executed it. A symbol executed by most
// of the suite is framework, logging or DI plumbing, not feature code; the
// ubiquity cutoff uses this to keep shared runtime out of every surface.
func (q *Queries) SymbolTestFanIn(ctx context.Context, runID int64) ([]SymbolTestFanInRow, error) {
	rows, err := q.db.QueryContext(ctx, symbolTestFanIn, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolTestFanInRow{}
	for rows.Next() {
		var i SymbolTestFanInRow
		if err := rows.Scan(&i.SymbolID, &i.TestCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
