package doctor

import (
	"os"
	"path/filepath"
	"testing"
)

// A working tree that matches every recorded hash is the only state that
// earns an "ok" from this check.
func TestIndexFreshness_TreeMatchesIndex_OK(t *testing.T) {
	f := newFixture(t)
	f.indexFile(t, "pkg/a.go", "package pkg\n\nfunc A() {}\n")
	f.indexFile(t, "pkg/b.go", "package pkg\n\nfunc B() {}\n")

	res := runCheck(t, indexFreshness{}, f.env(t))

	assertSeverity(t, res, SeverityOK)
	if got := res.Details["indexed_files"]; got != 2 {
		t.Errorf("indexed_files = %v, want 2", got)
	}
}

// The load-bearing case: a file edited since its scan means every number
// downstream is about content atlas has not read.
func TestIndexFreshness_ChangedFile_Fails(t *testing.T) {
	f := newFixture(t)
	f.indexFile(t, "pkg/a.go", "package pkg\n\nfunc A() {}\n")
	// Same path, different bytes, hash row left alone.
	f.writeFile(t, "pkg/a.go", "package pkg\n\nfunc A() { println(1) }\n")

	res := runCheck(t, indexFreshness{}, f.env(t))

	assertSeverity(t, res, SeverityFail)
	if got := res.Details["changed"]; got != 1 {
		t.Errorf("changed = %v, want 1", got)
	}
	if res.Remediation == "" {
		t.Error("a stale index must name the command that fixes it")
	}
}

// A deleted file leaves symbols in the store that nothing on disk backs.
func TestIndexFreshness_DeletedFile_Fails(t *testing.T) {
	f := newFixture(t)
	f.indexFile(t, "pkg/a.go", "package pkg\n\nfunc A() {}\n")
	f.indexFile(t, "pkg/gone.go", "package pkg\n\nfunc Gone() {}\n")
	if err := os.Remove(filepath.Join(f.root, "pkg", "gone.go")); err != nil {
		t.Fatalf("remove: %v", err)
	}

	res := runCheck(t, indexFreshness{}, f.env(t))

	assertSeverity(t, res, SeverityFail)
	if got := res.Details["missing"]; got != 1 {
		t.Errorf("missing = %v, want 1", got)
	}
	if paths, _ := res.Details["missing_files"].([]string); len(paths) != 1 || paths[0] != "pkg/gone.go" {
		t.Errorf("missing_files = %v, want [pkg/gone.go]", res.Details["missing_files"])
	}
}

// A source file the scan never reached is a hole in the picture, but not
// a lie about what atlas did read -- warn, not fail.
func TestIndexFreshness_UnindexedGoFile_Warns(t *testing.T) {
	f := newFixture(t)
	f.indexFile(t, "pkg/a.go", "package pkg\n\nfunc A() {}\n")
	f.writeFile(t, "pkg/new.go", "package pkg\n\nfunc New() {}\n")

	res := runCheck(t, indexFreshness{}, f.env(t))

	assertSeverity(t, res, SeverityWarn)
	if got := res.Details["unindexed"]; got != 1 {
		t.Errorf("unindexed = %v, want 1", got)
	}
}

// Excluded-by-policy files are not evidence of a stale index. Reporting
// them would train users to ignore the check.
func TestIndexFreshness_GeneratedAndSkippedFilesAreNotUnindexed(t *testing.T) {
	f := newFixture(t)
	f.indexFile(t, "pkg/a.go", "package pkg\n\nfunc A() {}\n")
	f.writeFile(t, "pkg/zz_gen.go",
		"// Code generated by stringer. DO NOT EDIT.\n\npackage pkg\n")
	f.writeFile(t, "internal/generated/api.go", "package generated\n")
	f.writeFile(t, "vendor/x/x.go", "package x\n")
	f.writeFile(t, ".hidden/h.go", "package h\n")

	env := f.env(t)
	env.SkipDirs = []string{"vendor"}
	res := runCheck(t, indexFreshness{}, env)

	assertSeverity(t, res, SeverityOK)
	if got := res.Details["unindexed"]; got != 0 {
		t.Errorf("unindexed = %v, want 0 (samples: %v)", got, res.Details["unindexed_files"])
	}
}

// A configured scan.generated glob is policy too, and doctor is handed
// the same list the scanner used.
func TestIndexFreshness_ConfiguredGeneratedGlobExcluded(t *testing.T) {
	f := newFixture(t)
	f.indexFile(t, "pkg/a.go", "package pkg\n\nfunc A() {}\n")
	f.writeFile(t, "pkg/api.pb.go", "package pkg\n")

	env := f.env(t)
	env.GeneratedGlobs = []string{"**/*.pb.go"}
	res := runCheck(t, indexFreshness{}, env)

	assertSeverity(t, res, SeverityOK)
}

// A store that has never been scanned cannot answer anything, and saying
// so is more useful than reporting a vacuously clean index.
func TestIndexFreshness_NoIndexAtAll_Fails(t *testing.T) {
	f := newFixture(t)
	f.writeFile(t, "pkg/a.go", "package pkg\n\nfunc A() {}\n")

	res := runCheck(t, indexFreshness{}, f.env(t))

	assertSeverity(t, res, SeverityFail)
	if res.Remediation == "" {
		t.Error("an empty index must name the command that fills it")
	}
}

// `atlas scan --hash-files=false` produces symbols with no hashes. There
// is nothing to compare against, so the honest answer is "cannot tell",
// never "ok" -- this is the exact lie the check set is built to avoid.
func TestIndexFreshness_SymbolsButNoHashes_NotApplicable(t *testing.T) {
	f := newFixture(t)
	f.writeFile(t, "pkg/a.go", "package pkg\n\nfunc A() {}\n")
	f.insertSymbol(t, "pkg.A", "pkg/a.go", 3)

	res := runCheck(t, indexFreshness{}, f.env(t))

	assertSeverity(t, res, SeverityNotApplicable)
}

// A .go file with no hash row but with indexed symbols WAS scanned; only
// its hash is missing. Counting it as unindexed would be a false alarm.
func TestIndexFreshness_FileWithSymbolsIsNotUnindexed(t *testing.T) {
	f := newFixture(t)
	f.indexFile(t, "pkg/a.go", "package pkg\n\nfunc A() {}\n")
	f.writeFile(t, "pkg/b.go", "package pkg\n\nfunc B() {}\n")
	f.insertSymbol(t, "pkg.B", "pkg/b.go", 3)

	res := runCheck(t, indexFreshness{}, f.env(t))

	assertSeverity(t, res, SeverityOK)
}

// Without a store there is nothing to compare the tree to.
func TestIndexFreshness_NoStore_NotApplicable(t *testing.T) {
	f := newFixture(t)
	env := f.env(t)
	env.Store = nil

	res := runCheck(t, indexFreshness{}, env)

	assertSeverity(t, res, SeverityNotApplicable)
}
