package contract

import (
	"context"
	"fmt"
	"strings"

	"github.com/sosalejandro/atlas/packages/shared"
	"github.com/sosalejandro/atlas/packages/store"
)

// PersistOptions configures Persist.
type PersistOptions struct {
	// IDPrefix is prepended to every auto-generated contract feature ID
	// (the ones that don't carry an explicit @atlas:contract annotation).
	// Defaults to "contract" which produces IDs like
	// "contract.api.v1.auth.login.post". Set to "" to skip the prefix.
	IDPrefix string

	// AutoGenerateIDs, when true, allows Persist to synthesise feature
	// IDs for contracts that don't carry an annotation. When false the
	// extractor only writes contracts whose FeatureID is non-nil — useful
	// for "annotation-driven only" deployments.
	AutoGenerateIDs bool
}

// PersistStats records what Persist wrote.
type PersistStats struct {
	FeaturesUpserted     int `json:"features_upserted"`
	FeatureSymbolsLinked int `json:"feature_symbols_linked"`
	Skipped              int `json:"skipped"`
}

// Persist writes a slice of ContractDef into the Store. Each ContractDef
// becomes one `features` row with kind = "contract"; every Symbol on the
// def gets a `feature_symbols` row with role = "contract" and source =
// "annotation" when FeatureID came from an annotation, "inferred"
// otherwise.
//
// Idempotent — re-running with the same defs is a no-op apart from
// refreshing updated_at on the features row.
//
// The implementation does NOT open a transaction itself; the underlying
// store ports each manage their own statements. If atomicity across all
// contracts is needed, the caller can wrap Persist in BeginTx (the Store
// supports tx-scoped queries via withTx).
func Persist(ctx context.Context, s *store.Store, defs []ContractDef, opts PersistOptions) (*PersistStats, error) {
	if s == nil {
		return nil, fmt.Errorf("contract persist: nil store")
	}
	stats := &PersistStats{}
	feats := s.Features()
	symbols := s.Symbols()
	links := s.FeatureSymbols()

	for _, d := range defs {
		fid, autogenerated := resolveFeatureID(d, opts)
		if fid == "" {
			stats.Skipped++
			continue
		}

		title := buildContractTitle(d)
		if err := feats.Upsert(ctx, store.Feature{
			ID:    fid,
			Title: title,
			Kind:  store.FeatureKindContract,
		}); err != nil {
			return stats, fmt.Errorf("contract persist: upsert feature %q: %w", fid, err)
		}
		stats.FeaturesUpserted++

		source := store.SourceAnnotation
		if autogenerated {
			source = store.SourceInferred
		}

		for _, symID := range d.Symbols {
			sym, err := symbols.FindByQualifiedName(ctx, symID)
			if err != nil {
				// Not every contract Symbol may have a symbols row (e.g.
				// route-only contracts where the handler hasn't been
				// ingested yet). Skip the link rather than abort the
				// whole persist run.
				continue
			}
			if err := links.Link(ctx, store.FeatureSymbolLink{
				FeatureID: fid,
				SymbolID:  sym.ID,
				Role:      store.RoleContract,
				Source:    source,
			}); err != nil {
				return stats, fmt.Errorf("contract persist: link %q→%d: %w", fid, sym.ID, err)
			}
			stats.FeatureSymbolsLinked++
		}
	}
	return stats, nil
}

// resolveFeatureID returns the FeatureID to persist for a def plus
// whether it was auto-generated (vs annotation-supplied).
//
// Precedence:
//   1. def.FeatureID (annotation hit).
//   2. opts.AutoGenerateIDs => synthesise from Kind + Operation/Name.
//   3. otherwise "" (signals "skip").
func resolveFeatureID(d ContractDef, opts PersistOptions) (shared.FeatureID, bool) {
	if d.FeatureID != nil && *d.FeatureID != "" {
		return *d.FeatureID, false
	}
	if !opts.AutoGenerateIDs {
		return "", false
	}
	id := synthFeatureID(d, opts.IDPrefix)
	return id, true
}

// synthFeatureID builds a deterministic feature ID for an
// annotation-free contract. The shape mirrors docs/annotations.md ID
// rules (lowercase, dot-namespaced, [a-z0-9_]+).
//
// Examples:
//
//	{Kind: huma-op, OperationID: createPlatformSubscription} →
//	  contract.huma.createplatformsubscription
//	{Kind: route, Method: POST, Path: /api/v1/auth/login} →
//	  contract.route.post.api.v1.auth.login
//	{Kind: graphql, Name: Mutation.foo} →
//	  contract.graphql.mutation.foo
//	{Kind: func, Symbols: [AuthHandler.Login]} →
//	  contract.func.authhandler.login
func synthFeatureID(d ContractDef, prefix string) shared.FeatureID {
	parts := []string{}
	if prefix != "" {
		parts = append(parts, prefix)
	}
	switch d.Kind {
	case KindHumaOp:
		parts = append(parts, "huma")
		if d.Operation.OperationID != "" {
			parts = append(parts, d.Operation.OperationID)
		} else {
			parts = append(parts, d.Operation.Method, d.Operation.Path)
		}
	case KindRoute:
		parts = append(parts, "route", d.Operation.Method, d.Operation.Path)
	case KindGraphQL:
		parts = append(parts, "graphql", d.Name)
	case KindFunc:
		parts = append(parts, "func", d.Name)
		if len(d.Symbols) > 0 {
			parts = append(parts, string(d.Symbols[0]))
		}
	default:
		parts = append(parts, string(d.Kind), d.Name)
	}
	joined := strings.Join(parts, ".")
	return shared.FeatureID(sanitiseID(joined))
}

// sanitiseID lower-cases the input and collapses any character outside
// [a-z0-9_] into a dot. Multiple consecutive dots collapse to a single
// dot; leading/trailing dots are trimmed.
func sanitiseID(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z',
			r >= '0' && r <= '9',
			r == '_',
			r == '.':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + ('a' - 'A'))
		default:
			b.WriteRune('.')
		}
	}
	// Collapse runs of dots + trim.
	s = b.String()
	for strings.Contains(s, "..") {
		s = strings.ReplaceAll(s, "..", ".")
	}
	return strings.Trim(s, ".")
}

// buildContractTitle returns a short, human-readable title for the
// features row. We deliberately don't dump the full signature into the
// title — the SQLite features table is meant to be browsed, and the
// signature lives elsewhere (the in-memory ContractDef + future
// schema-side columns).
func buildContractTitle(d ContractDef) string {
	switch d.Kind {
	case KindHumaOp:
		if d.Operation.Summary != "" {
			return d.Operation.Summary
		}
		if d.Operation.OperationID != "" {
			return d.Operation.OperationID
		}
		return strings.TrimSpace(d.Operation.Method + " " + d.Operation.Path)
	case KindRoute:
		return strings.TrimSpace(d.Operation.Method + " " + d.Operation.Path)
	case KindGraphQL:
		return d.Name
	case KindFunc:
		return d.Name
	default:
		return d.Name
	}
}
